/**
 * Auto-generated by scripts/build_detail_page_js.py.
 *
 * This file is for the mini-program detail page only.
 * It intentionally excludes search-only metadata such as:
 *   - search
 *   - searchmeta
 *   - ranking
 *   - pinyin / pinyinAbbr and other search keys under search.*
 *
 * Top-level export:
 *   module.exports = { [id]: DetailRecord }
 *
 * DetailRecord core fields:
 *   - id: stable content id from meta.json:id
 *   - title: display title from meta.json:core.title
 *   - display_version: currently 2, meaning structured latex-first sections are available
 *   - sections: structured display sections built from raw tex before clean_tex
 *
 * DetailRecord metadata fields:
 *   - module: Logical module name from meta.json; source=module; why=Lets the detail page know the business module without using the directory name.
 *   - alias: Alternative titles or aliases; source=core.alias; why=Useful for secondary display, FAQ labels, or future content hints.
 *   - difficulty: Difficulty level; source=core.difficulty; why=Supports badges, filtering, or display of expected problem difficulty.
 *   - category: Primary topic category; source=core.category; why=Supports detail-page labeling and page-level context.
 *   - tags: Topic tags; source=core.tags; why=Useful for related content chips and page-level navigation.
 *   - core_summary: Short summary from core metadata; source=core.summary; why=Keeps a compact summary separate from the long cleaned `summary` field.
 *   - core_formula: Primary formula or theorem statement; source=math.core_formula; why=Usually the first math block the detail page wants to highlight.
 *   - related_formulas: Closely related formulas; source=math.related_formulas; why=Supports extended reading and future expandable formula panels.
 *   - variables: Variables used by the formula; source=math.variables; why=Helps the detail page explain notation without re-parsing the formula text.
 *     variables shape: [{ latex, description? }] so the front end can render variables as math.
 *   - conditions: Conditions under which the statement holds; source=math.conditions; why=Important guardrails for the detail page so conditions are easy to show.
 *   - conclusions: Main conclusion or equality case; source=math.conclusions; why=Lets the page show the takeaway without re-reading the full proof.
 *   - usage: Usage scenarios and problem types; source=usage; why=Supports 'when to use this' sections on the detail page.
 *   - interactive: Interactive page configuration; source=interactive; why=Keeps detail-page interactive affordances close to the content record.
 *   - assets: Static asset references; source=assets; why=The detail page can directly load svg, png, mp4, or other resources.
 *   - shareConfig: Share card title and description; source=shareConfig; why=Used directly by the mini-program sharing entry points.
 *   - relations: Prerequisites and related content; source=relations; why=Supports related-content blocks and learning-path navigation.
 *   - isPro: Premium or gated flag; source=isPro; why=Allows the page to show lock states or access messaging.
 *   - remarks: Free-form remarks; source=remarks; why=Keeps room for editorial notes without changing the schema.
 *   - knowledgeNode: Primary knowledge-tree node; source=knowledgeNode; why=Useful for breadcrumb-like display or curriculum linking.
 *   - altNodes: Alternative knowledge-tree nodes; source=altNodes; why=Supports cross-linking when one topic belongs to multiple paths.
 *
 * DetailRecord cleaned text fields:
 *   - statement: Main cleaned theorem/problem statement; source=01_statement.tex; fallback=content.statement; why=This is the primary content block shown at the top of the detail page.
 *   - explanation: Cleaned explanatory text; source=02_explanation.tex; fallback=none; why=Used for intuition, decomposition, and interpretation under the statement.
 *   - proof: Cleaned proof text; source=03_proof.tex; fallback=none; why=Keeps the formal derivation in display-ready plain text.
 *   - examples: Cleaned examples text; source=04_examples.tex; fallback=none; why=Supports worked examples or application snippets on the detail page.
 *   - traps: Cleaned common pitfalls text; source=05_traps.tex; fallback=content.common_tricks; why=Useful for mistake reminders and learning notes.
 *   - summary: Cleaned summary text; source=06_summary.tex; fallback=core.summary; why=Provides a concise end-of-page takeaway for quick review.
 *
 * Structured sections schema:
 *   - Section = { key, title, layout, items }
 *   - Supported item forms:
 *     1. { text: string }
 *     2. { latex: string }
 *     3. { segments: [{ type: 'text', text } | { type: 'math', latex }] }
 *     4. theorem-list item: { title, segments }
 *   - Rich parser rules for mixed text/math sections:
 *     - Long equation-chain math is promoted to standalone { latex } items.
 *     - Trailing punctuation is stripped out of latex and kept in text segments.
 *     - This improves canonical migration to math_block and avoids inline overflow.
 *   - Important layouts used by this builder:
 *     - text
 *     - theorem-list
 *   - Legacy plain-text fields remain in the record for compatibility and debugging.
 */
module.exports = {
  "C052": {
    "id": "C052",
    "title": "椭圆焦点弦长公式",
    "module": "conic",
    "alias": [
      "焦点弦长",
      "椭圆焦点弦",
      "焦点弦长公式",
      "通径公式"
    ],
    "difficulty": 3,
    "category": "解析几何",
    "tags": [
      "椭圆焦点弦",
      "弦长公式",
      "圆锥曲线",
      "二级结论",
      "通径"
    ],
    "core_summary": "已知倾斜角直接求过焦点的弦长，避免联立方程组。",
    "core_formula": "L = \\frac{2ab^2}{a^2 - c^2\\cos^2\\theta}",
    "related_formulas": [
      "L = \\frac{2b^2}{a}（当\\theta=90^\\circ）"
    ],
    "variables": [],
    "conditions": "椭圆标准方程为$\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1$（$a>b>0$），焦点在$x$轴上，弦过焦点，倾斜角$\\theta$。",
    "conclusions": "焦点弦长$L$由公式给出；当$\\theta=90^\\circ$时，$L=\\frac{2b^2}{a}$（通径）。",
    "usage": {
      "scenarios": [
        "解析几何计算题",
        "压轴题中段",
        "已知弦长求参数"
      ],
      "problem_types": [
        "焦点弦长计算",
        "逆向求倾斜角或椭圆方程",
        "综合最值问题"
      ],
      "exam_frequency": 0.8,
      "exam_score": 5
    },
    "interactive": {
      "has_diagram": true,
      "geogebra_id": "",
      "param_demo": {}
    },
    "assets": {
      "svg": "",
      "image": "",
      "video": ""
    },
    "shareConfig": {
      "title": "椭圆焦点弦长公式：倾斜角直接求弦长",
      "shareDesc": "适合解析几何计算题，减少联立过程，快速得到过焦点弦长，避免代数错误，提升解题稳定性。"
    },
    "relations": {
      "prerequisites": [
        "椭圆标准方程",
        "直线与椭圆联立",
        "韦达定理"
      ],
      "related_ids": [],
      "similar": "类似结论包括双曲线焦点弦长公式、抛物线焦点弦长公式。"
    },
    "isPro": 0,
    "remarks": "",
    "knowledgeNode": "解析几何-圆锥曲线-椭圆",
    "altNodes": [
      "解析几何-圆锥曲线-双曲线",
      "解析几何-圆锥曲线-抛物线",
      "解析几何-综合-最值问题"
    ],
    "statement": "条件\n- 条件1（椭圆方程）：\n焦点在 x 轴上的椭圆 (x^2) / (a^2)+(y^2) / (b^2)=1（a>b>0），半焦距 c=sqrt(a^2-b^2)。\n- 条件2（焦点弦）：\n弦过椭圆的一个焦点，且弦所在直线的倾斜角为 （与 x 轴正方向夹角）。\n结论\n- 结论一（焦点弦长）：\n直观描述：\n焦点弦长由半长轴、半短轴和倾斜角决定。\nL = (2ab^2) / (a^2 - c^2 ^2 ),\n其中 c = sqrt(a^2-b^2)。\n- 推广结论（通径特例）：\n直观描述：\n当弦与 x 轴垂直时，弦长等于通径长。\nL = (2b^2) / (a).",
    "explanation": "一句话直觉\n只需知道椭圆的半长轴 a、半短轴 b 和直线的倾斜角 ，直接代入公式即可得到焦点弦长，无需联立方程组。\n核心拆解\n- 要点一（直线参数化）：\n过焦点的直线用倾斜角 表示参数方程，代入椭圆方程。\n- 要点二（韦达定理）：\n利用韦达定理求出两个交点对应的参数差，从而得到焦点弦长公式\nL=(2ab^2) / (a^2-c^2 ^2 ).\n几何本质（方向决定弦长）\n焦点弦长 L 依赖于 a、b 和 ^2 。\n当 =90^ 时， ^2 =0，分母最大，弦长最短：\nL=(2b^2) / (a),\n这就是椭圆的通径长。\n当 =0^ 时， ^2 =1，分母最小，弦长最长：\nL=2a.\n代数意义（三角分式）\n公式\nL=(2ab^2) / (a^2-c^2 ^2 )\n可以看成关于 ^2 的分式函数。因为\n0 <= ^2 <= 1,\n所以分母在\nb^2 <= a^2-c^2 ^2 <= a^2\n之间变化，从而弦长在\n(2b^2) / (a) <= L <= 2a\n之间变化。\n考点价值（弦长与最值）\n- 考法一（直接代入）： 已知椭圆方程和焦点弦倾斜角，直接代入公式计算弦长。\n- 考法二（最值问题）： 由 ^2 的取值范围 [0,1] 求弦长最值，常结合离心率。\n- 考法三（反求参数）： 已知焦点弦长，反求倾斜角、离心率或椭圆参数。\n顿悟点\n这类题的关键不是盲目联立，而是看到“过焦点的弦”后，想到用焦点作为起点建立参数方程。这样两个交点对应的参数差，正好就是弦长。\n使用场景\n- 场景一（直接求弦长）： 题目给出倾斜角或斜率，求焦点弦长。\n- 场景二（求最值范围）： 题目要求焦点弦长的最大值、最小值或取值范围。\n- 场景三（反求椭圆参数）： 已知焦点弦长和角度信息，反推出 a,b,c 或离心率。",
    "proof": "思路提示\n利用直线的参数方程（用倾斜角 表示），代入椭圆方程转化为关于参数 t 的二次方程，通过韦达定理和弦长公式化简得到结果。\n正式推导\n- 步骤一（参数方程引入）：\n设椭圆右焦点 F(c,0)，过 F 且倾斜角为 的直线参数方程为\nx = c + t ,\\\\\ny = t ,\n其中 t 为参数，表示点 P 到 F 的有向距离。\n理由： 参数方程能直接表达直线上点的坐标与距离的关系，便于后续计算弦长。\n- 步骤二（联立椭圆方程）：\n将参数方程代入椭圆 (x^2) / (a^2)+(y^2) / (b^2)=1：\n((c+t )^2) / (a^2)+((t )^2) / (b^2)=1.\n展开并整理，得到关于 t 的二次方程\n(( ^2 ) / (a^2)+( ^2 ) / (b^2))t^2+(2c ) / (a^2)t+((c^2) / (a^2)-1)=0.\n由 c^2=a^2-b^2 得常数项 (c^2) / (a^2)-1=-(b^2) / (a^2)。\n理由： 通过代入消元得到参数 t 满足的二次方程，为使用韦达定理做准备。\n- 步骤三（韦达定理与判别式）：\n记 A=( ^2 ) / (a^2)+( ^2 ) / (b^2), B=(2c ) / (a^2), C=-(b^2) / (a^2)。\nt_1+t_2=-(B) / (A), t_1t_2=(C) / (A).\n计算判别式 = B^2-4AC。\nB^2 &= (4c^2 ^2 ) / (a^4),\\\\\n4AC &= 4 * (( ^2 ) / (a^2)+( ^2 ) / (b^2)) * (-(b^2) / (a^2)) \\\\\n&= -(4b^2 ^2 ) / (a^4)-(4 ^2 ) / (a^2).\n所以\n&= (4c^2 ^2 ) / (a^4)+(4b^2 ^2 ) / (a^4)+(4 ^2 ) / (a^2) \\\\\n&= (4 ^2 (a^2-b^2+b^2)) / (a^4)+(4 ^2 ) / (a^2) \\\\\n&= (4 ^2 ) / (a^2)+(4 ^2 ) / (a^2) \\\\\n&= (4) / (a^2).\n理由： 韦达定理给出和与积，判别式反映参数差值的平方，直接代入弦长公式。\n- 步骤四（弦长公式化简）：\n弦长 L 等于 |t_1-t_2|，即\nL = |t_1-t_2| = sqrt((t_1+t_2)^2-4t_1t_2) = (sqrt( )) / (|A|).\n代入 sqrt( )=(2) / (a)，A=( ^2 ) / (a^2)+( ^2 ) / (b^2)>0，得\nL &= (2/a) / (( ^2 ) / (a^2)+( ^2 ) / (b^2)) \\\\\n&= (2ab^2) / (b^2 ^2 +a^2 ^2 ).\n利用 a^2 ^2 +b^2 ^2 = a^2-(a^2-b^2) ^2 = a^2-c^2 ^2 ，即得\nL = (2ab^2) / (a^2-c^2 ^2 ).\n理由： 分母恒等变形使表达式更简洁，且突出离心率的影响。\n结论回扣\n至此，椭圆焦点弦长公式得证。当 =90^ 时， =0，代入得 L=(2b^2) / (a)，即为通径长。该公式提供了已知倾斜角直接计算焦点弦长的便捷途径。",
    "examples": "例 1（基础）\n题目： 已知椭圆 (x^2) / (4)+(y^2) / (3)=1，过右焦点且倾斜角为 60^ 的直线交椭圆于 A,B 两点，求弦 AB 的长。\n解题步骤：\n- 第一步（确定参数）：\n由椭圆方程得 a=2，b^2=3，c=sqrt(a^2-b^2)=1，倾斜角 =60^ ， = 12。\n理由： 代入公式需要这些量。\n- 第二步（代入公式）：\n焦点弦长公式 L=(2ab^2) / (a^2-c^2 ^2 )，代入得\nL &= (2 * 2 * 3) / (4-1 * ( 12)^2) \\\\\n&= (12) / (4- 14) \\\\\n&= (12) / ((15) / (4)) \\\\\n&= (48) / (15) \\\\\n&= (16) / (5).\n理由： 直接计算即得。\n- 第三步（给出结论）：\n所以 |AB|=(16) / (5)。\n理由： 根据计算得到最终答案。\n关键结论： |AB| = 5\n例 2（稍变形）\n题目： 已知椭圆 (x^2) / (4)+(y^2) / (3)=1，过右焦点且倾斜角为 的焦点弦长等于 (16) / (5)，求 的值。\n解题步骤：\n- 第一步（代入公式）：\n由公式 L=(2ab^2) / (a^2-c^2 ^2 )，得 (16) / (5) = (12) / (4- ^2 )。\n理由： 已知 a=2,b^2=3,c=1，代入化简。\n- 第二步（解方程）：\n分母乘过去：\n16(4- ^2 ) &= 60 \\\\\n64 - 16 ^2 &= 60 \\\\\n16 ^2 &= 4 \\\\\n^2 &= 14 \\\\\n&= 12.\n理由： 代数变形解出 ^2 ，注意开方有正负。\n- 第三步（结论）：\n所以 = 12。\n理由： 倾斜角 范围 [0, )，余弦可正可负，均能使弦长成立。\n关键结论： = 12\n例 3（综合应用）\n题目： 已知椭圆 (x^2) / (a^2)+(y^2) / (b^2)=1（a>b>0）的离心率 e= 12，过右焦点且倾斜角为 60^ 的直线被椭圆截得的弦长等于 (16) / (5)，求椭圆方程。\n解题步骤：\n- 第一步（利用离心率）：\n由 e=(c) / (a)= 12 得 c= a2，从而 b^2=a^2-c^2=a^2-(a^2) / (4)=(3a^2) / (4)。\n理由： 离心率给出 a,b,c 的关系。\n- 第二步（代入弦长公式）：\n=60^ ， = 12，代入公式 L=(2ab^2) / (a^2-c^2 ^2 ) 得\nL &= (2a * (3a^2) / (4)) / (a^2-(a^2) / (4) * 14) \\\\\n&= ((3a^3) / (2)) / (a^2-(a^2) / (16)) \\\\\n&= ((3a^3) / (2)) / ((15a^2) / (16)) \\\\\n&= (3a^3) / (2) * (16) / (15a^2) \\\\\n&= (8a) / (5).\n理由： 利用 a 表达 L，化简为 8a/5。\n- 第三步（求 a）：\n令 (8a) / (5)=(16) / (5)，解得 a=2。于是 c=1，b^2=3。\n理由： 由待定系数法求出 a，再回代得 b。\n- 第四步（结论）：\n椭圆方程为 (x^2) / (4)+(y^2) / (3)=1。\n理由： 代入标准形式即得。\n关键结论： 4+3=1",
    "traps": "- 易错点一（条件遗漏）\n使用公式时未验证椭圆是否满足焦点在 x 轴的标准形式，以及直线是否确实过焦点。\n- 正确理解（条件验证）：\n公式仅适用于焦点在 x 轴上的椭圆，且直线过该焦点；若焦点在 y 轴或直线不过焦点，公式不成立。\n- 错因分析（忽视前提）：\n学生看到“弦长”“椭圆”等关键字就机械套用公式，忽略公式的适用前提。\n- 易错点二（平方漏写）\n将公式分母误写为 a^2-c^2 ，缺少 ^2 中的平方。\n- 正确理解（平方形式）：\n分母中的 ^2 来源于参数 t 系数中的 平方，且平方后保证了分母非负。\n- 错因分析（平方缺失）：\n学生平时用 表示方向向量时常忘记平方，导致符号错误。\n- 易错点三（通径记反）\n将通径长记作 (2a^2) / (b) 或 (2a) / (b^2)，混淆 a 与 b 的位置。\n- 正确理解（通径推导）：\n由公式当 =90^ 时得 L=(2b^2) / (a)，也可从几何意义：通径是过焦点垂直于长轴的弦，长为 2b^2/a。\n- 错因分析（记忆混淆）：\n学生未从推导记忆，仅靠机械记忆，导致 a、b 位置颠倒。",
    "summary": "一句话核心\n焦点弦长公式：已知倾斜角直接求过焦点的弦长，避免联立方程组。\n使用条件\n- 条件 1（椭圆标准）： 焦点在 x 轴上的椭圆，a>b>0。\n- 条件 2（直线条件）： 弦过椭圆焦点，且倾斜角 为直线与 x 轴正方向夹角。\n关键提醒\n- 易错点（公式前提）： 检查椭圆焦点位置和直线是否过焦点；分母是 a^2-c^2 ^2 ，注意 ^2 。\n- 检查项（通径检验）： 令 =90^ 得 L=2b^2/a，可验证公式是否正确。",
    "display_version": 2,
    "sections": [
      {
        "key": "core_formula",
        "title": "核心公式",
        "layout": "text",
        "items": [
          {
            "latex": "L = \\frac{2ab^2}{a^2 - c^2\\cos^2\\theta}"
          }
        ]
      },
      {
        "key": "conditions",
        "title": "适用条件",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "椭圆标准方程为"
              },
              {
                "type": "math",
                "latex": "\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1"
              },
              {
                "type": "text",
                "text": "（"
              },
              {
                "type": "math",
                "latex": "a>b>0"
              },
              {
                "type": "text",
                "text": "），焦点在"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴上，弦过焦点，倾斜角"
              },
              {
                "type": "math",
                "latex": "\\theta"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          }
        ]
      },
      {
        "key": "statement",
        "title": "命题表述",
        "layout": "theorem-list",
        "items": [
          {
            "title": "条件1（椭圆方程）：",
            "segments": [
              {
                "type": "text",
                "text": "焦点在"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴上的椭圆"
              },
              {
                "type": "math",
                "latex": "\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1"
              },
              {
                "type": "text",
                "text": "（"
              },
              {
                "type": "math",
                "latex": "a>b>0"
              },
              {
                "type": "text",
                "text": "），半焦距"
              },
              {
                "type": "math",
                "latex": "c=\\sqrt{a^2-b^2}"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "title": "条件2（焦点弦）：",
            "segments": [
              {
                "type": "text",
                "text": "弦过椭圆的一个焦点，且弦所在直线的倾斜角为"
              },
              {
                "type": "math",
                "latex": "\\theta"
              },
              {
                "type": "text",
                "text": "（与"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴正方向夹角）。"
              }
            ]
          },
          {
            "title": "结论一（焦点弦长）：",
            "segments": [
              {
                "type": "text",
                "text": "焦点弦长由半长轴、半短轴和倾斜角决定。"
              },
              {
                "type": "math",
                "latex": "L = \\frac{2ab^2}{a^2 - c^2\\cos^2\\theta},"
              },
              {
                "type": "text",
                "text": "其中"
              },
              {
                "type": "math",
                "latex": "c = \\sqrt{a^2-b^2}"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "title": "推广结论（通径特例）：",
            "segments": [
              {
                "type": "text",
                "text": "当弦与"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴垂直时，弦长等于通径长。"
              },
              {
                "type": "math",
                "latex": "L = \\frac{2b^2}{a}."
              }
            ]
          }
        ]
      },
      {
        "key": "explanation",
        "title": "理解与直觉",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "一句话直觉\n只需知道椭圆的半长轴"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "、半短轴"
              },
              {
                "type": "math",
                "latex": "b"
              },
              {
                "type": "text",
                "text": "和直线的倾斜角"
              }
            ]
          },
          {
            "latex": "\\theta"
          },
          {
            "text": "，直接代入公式即可得到焦点弦长，无需联立方程组。"
          },
          {
            "text": "核心拆解"
          },
          {
            "text": "要点一（直线参数化）：\n过焦点的直线用倾斜角"
          },
          {
            "latex": "\\theta"
          },
          {
            "text": "表示参数方程，代入椭圆方程。"
          },
          {
            "text": "要点二（韦达定理）：\n利用韦达定理求出两个交点对应的参数差，从而得到焦点弦长公式"
          },
          {
            "latex": "L=\\frac{2ab^2}{a^2-c^2\\cos^2\\theta}"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "几何本质（方向决定弦长）\n焦点弦长"
              },
              {
                "type": "math",
                "latex": "L"
              },
              {
                "type": "text",
                "text": "依赖于"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "、"
              },
              {
                "type": "math",
                "latex": "b"
              },
              {
                "type": "text",
                "text": "和"
              }
            ]
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "text": "。\n当"
          },
          {
            "latex": "\\theta=90^\\circ"
          },
          {
            "text": "时，"
          },
          {
            "latex": "\\cos^2\\theta=0"
          },
          {
            "text": "，分母最大，弦长最短："
          },
          {
            "latex": "L=\\frac{2b^2}{a}"
          },
          {
            "text": ",这就是椭圆的通径长。\n当"
          },
          {
            "latex": "\\theta=0^\\circ"
          },
          {
            "text": "时，"
          },
          {
            "latex": "\\cos^2\\theta=1"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，分母最小，弦长最长："
              },
              {
                "type": "math",
                "latex": "L=2a"
              },
              {
                "type": "text",
                "text": "."
              }
            ]
          },
          {
            "text": "代数意义（三角分式）\n公式"
          },
          {
            "latex": "L=\\frac{2ab^2}{a^2-c^2\\cos^2\\theta}"
          },
          {
            "text": "可以看成关于"
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "text": "的分式函数。因为"
          },
          {
            "latex": "0\\leq \\cos^2\\theta \\leq 1"
          },
          {
            "text": ",所以分母在"
          },
          {
            "latex": "b^2 \\leq a^2-c^2\\cos^2\\theta \\leq a^2"
          },
          {
            "text": "之间变化，从而弦长在"
          },
          {
            "latex": "\\frac{2b^2}{a} \\leq L \\leq 2a"
          },
          {
            "text": "之间变化。"
          },
          {
            "text": "考点价值（弦长与最值）"
          },
          {
            "text": "考法一（直接代入）： 已知椭圆方程和焦点弦倾斜角，直接代入公式计算弦长。"
          },
          {
            "text": "考法二（最值问题）： 由"
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "的取值范围"
              },
              {
                "type": "math",
                "latex": "[0,1]"
              },
              {
                "type": "text",
                "text": "求弦长最值，常结合离心率。"
              }
            ]
          },
          {
            "text": "考法三（反求参数）： 已知焦点弦长，反求倾斜角、离心率或椭圆参数。"
          },
          {
            "text": "顿悟点\n这类题的关键不是盲目联立，而是看到“过焦点的弦”后，想到用焦点作为起点建立参数方程。这样两个交点对应的参数差，正好就是弦长。"
          },
          {
            "text": "使用场景"
          },
          {
            "text": "场景一（直接求弦长）： 题目给出倾斜角或斜率，求焦点弦长。"
          },
          {
            "text": "场景二（求最值范围）： 题目要求焦点弦长的最大值、最小值或取值范围。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "场景三（反求椭圆参数）： 已知焦点弦长和角度信息，反推出"
              },
              {
                "type": "math",
                "latex": "a,b,c"
              },
              {
                "type": "text",
                "text": "或离心率。"
              }
            ]
          }
        ]
      },
      {
        "key": "proof",
        "title": "证明过程",
        "layout": "text",
        "items": [
          {
            "text": "思路提示\n利用直线的参数方程（用倾斜角"
          },
          {
            "latex": "\\theta"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "表示），代入椭圆方程转化为关于参数"
              },
              {
                "type": "math",
                "latex": "t"
              },
              {
                "type": "text",
                "text": "的二次方程，通过韦达定理和弦长公式化简得到结果。"
              }
            ]
          },
          {
            "text": "正式推导"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤一（参数方程引入）：\n设椭圆右焦点"
              },
              {
                "type": "math",
                "latex": "F(c,0)"
              },
              {
                "type": "text",
                "text": "，过"
              },
              {
                "type": "math",
                "latex": "F"
              },
              {
                "type": "text",
                "text": "且倾斜角为"
              }
            ]
          },
          {
            "latex": "\\theta"
          },
          {
            "text": "的直线参数方程为"
          },
          {
            "latex": "\\begin{cases}\nx = c + t\\cos\\theta,\\\\\ny = t\\sin\\theta,\n\\end{cases}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "其中"
              },
              {
                "type": "math",
                "latex": "t"
              },
              {
                "type": "text",
                "text": "为参数，表示点"
              },
              {
                "type": "math",
                "latex": "P"
              },
              {
                "type": "text",
                "text": "到"
              },
              {
                "type": "math",
                "latex": "F"
              },
              {
                "type": "text",
                "text": "的有向距离。\n理由： 参数方程能直接表达直线上点的坐标与距离的关系，便于后续计算弦长。"
              }
            ]
          },
          {
            "text": "步骤二（联立椭圆方程）：\n将参数方程代入椭圆"
          },
          {
            "latex": "\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1"
          },
          {
            "text": "："
          },
          {
            "latex": "\\frac{(c+t\\cos\\theta)^2}{a^2}+\\frac{(t\\sin\\theta)^2}{b^2}=1"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".展开并整理，得到关于"
              },
              {
                "type": "math",
                "latex": "t"
              },
              {
                "type": "text",
                "text": "的二次方程"
              }
            ]
          },
          {
            "latex": "\\left(\\frac{\\cos^2\\theta}{a^2}+\\frac{\\sin^2\\theta}{b^2}\\right)t^2+\\frac{2c\\cos\\theta}{a^2}t+\\left(\\frac{c^2}{a^2}-1\\right)=0"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".由"
              },
              {
                "type": "math",
                "latex": "c^2=a^2-b^2"
              },
              {
                "type": "text",
                "text": "得常数项"
              }
            ]
          },
          {
            "latex": "\\frac{c^2}{a^2}-1=-\\frac{b^2}{a^2}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "。\n理由： 通过代入消元得到参数"
              },
              {
                "type": "math",
                "latex": "t"
              },
              {
                "type": "text",
                "text": "满足的二次方程，为使用韦达定理做准备。"
              }
            ]
          },
          {
            "text": "步骤三（韦达定理与判别式）：\n记"
          },
          {
            "latex": "A=\\frac{\\cos^2\\theta}{a^2}+\\frac{\\sin^2\\theta}{b^2}"
          },
          {
            "text": ","
          },
          {
            "latex": "B=\\frac{2c\\cos\\theta}{a^2}"
          },
          {
            "text": ","
          },
          {
            "latex": "C=-\\frac{b^2}{a^2}"
          },
          {
            "text": "。"
          },
          {
            "latex": "t_1+t_2=-\\frac{B}{A},\\quad t_1t_2=\\frac{C}{A}"
          },
          {
            "text": ".计算判别式"
          },
          {
            "latex": "\\Delta = B^2-4AC"
          },
          {
            "text": "。"
          },
          {
            "latex": "\\begin{aligned}\nB^2 &= \\frac{4c^2\\cos^2\\theta}{a^4},\\\\\n4AC &= 4\\cdot\\left(\\frac{\\cos^2\\theta}{a^2}+\\frac{\\sin^2\\theta}{b^2}\\right)\\cdot\\left(-\\frac{b^2}{a^2}\\right) \\\\\n&= -\\frac{4b^2\\cos^2\\theta}{a^4}-\\frac{4\\sin^2\\theta}{a^2}.\n\\end{aligned}"
          },
          {
            "text": "所以"
          },
          {
            "latex": "\\begin{aligned}\n\\Delta &= \\frac{4c^2\\cos^2\\theta}{a^4}+\\frac{4b^2\\cos^2\\theta}{a^4}+\\frac{4\\sin^2\\theta}{a^2} \\\\\n&= \\frac{4\\cos^2\\theta(a^2-b^2+b^2)}{a^4}+\\frac{4\\sin^2\\theta}{a^2} \\\\\n&= \\frac{4\\cos^2\\theta}{a^2}+\\frac{4\\sin^2\\theta}{a^2} \\\\\n&= \\frac{4}{a^2}.\n\\end{aligned}"
          },
          {
            "text": "理由： 韦达定理给出和与积，判别式反映参数差值的平方，直接代入弦长公式。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤四（弦长公式化简）：\n弦长"
              },
              {
                "type": "math",
                "latex": "L"
              },
              {
                "type": "text",
                "text": "等于"
              },
              {
                "type": "math",
                "latex": "|t_1-t_2|"
              },
              {
                "type": "text",
                "text": "，即"
              }
            ]
          },
          {
            "latex": "L = |t_1-t_2| = \\sqrt{(t_1+t_2)^2-4t_1t_2} = \\frac{\\sqrt{\\Delta}}{|A|}"
          },
          {
            "text": ".代入"
          },
          {
            "latex": "\\sqrt{\\Delta}=\\frac{2}{a}"
          },
          {
            "text": "，"
          },
          {
            "latex": "A=\\frac{\\cos^2\\theta}{a^2}+\\frac{\\sin^2\\theta}{b^2}>0"
          },
          {
            "text": "，得"
          },
          {
            "latex": "\\begin{aligned}\nL &= \\frac{2/a}{\\frac{\\cos^2\\theta}{a^2}+\\frac{\\sin^2\\theta}{b^2}} \\\\\n&= \\frac{2ab^2}{b^2\\cos^2\\theta+a^2\\sin^2\\theta}.\n\\end{aligned}"
          },
          {
            "text": "利用"
          },
          {
            "latex": "a^2\\sin^2\\theta+b^2\\cos^2\\theta = a^2-(a^2-b^2)\\cos^2\\theta = a^2-c^2\\cos^2\\theta"
          },
          {
            "text": "，即得"
          },
          {
            "latex": "L = \\frac{2ab^2}{a^2-c^2\\cos^2\\theta}"
          },
          {
            "text": ".理由： 分母恒等变形使表达式更简洁，且突出离心率的影响。"
          },
          {
            "text": "结论回扣\n至此，椭圆焦点弦长公式得证。当"
          },
          {
            "latex": "\\theta=90^\\circ"
          },
          {
            "text": "时，"
          },
          {
            "latex": "\\cos\\theta=0"
          },
          {
            "text": "，代入得"
          },
          {
            "latex": "L=\\frac{2b^2}{a}"
          },
          {
            "text": "，即为通径长。该公式提供了已知倾斜角直接计算焦点弦长的便捷途径。"
          }
        ]
      },
      {
        "key": "examples",
        "title": "例题应用",
        "layout": "text",
        "items": [
          {
            "text": "例 1（基础）\n题目： 已知椭圆"
          },
          {
            "latex": "\\frac{x^2}{4}+\\frac{y^2}{3}=1"
          },
          {
            "text": "，过右焦点且倾斜角为"
          },
          {
            "latex": "60^\\circ"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "的直线交椭圆于"
              },
              {
                "type": "math",
                "latex": "A,B"
              },
              {
                "type": "text",
                "text": "两点，求弦"
              },
              {
                "type": "math",
                "latex": "AB"
              },
              {
                "type": "text",
                "text": "的长。\n解题步骤："
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第一步（确定参数）：\n由椭圆方程得"
              },
              {
                "type": "math",
                "latex": "a=2"
              },
              {
                "type": "text",
                "text": "，"
              },
              {
                "type": "math",
                "latex": "b^2=3"
              },
              {
                "type": "text",
                "text": "，"
              }
            ]
          },
          {
            "latex": "c=\\sqrt{a^2-b^2}=1"
          },
          {
            "text": "，倾斜角"
          },
          {
            "latex": "\\theta=60^\\circ"
          },
          {
            "text": "，"
          },
          {
            "latex": "\\cos\\theta=\\frac12"
          },
          {
            "text": "。\n理由： 代入公式需要这些量。"
          },
          {
            "text": "第二步（代入公式）：\n焦点弦长公式"
          },
          {
            "latex": "L=\\frac{2ab^2}{a^2-c^2\\cos^2\\theta}"
          },
          {
            "text": "，代入得"
          },
          {
            "latex": "\\begin{aligned}\nL &= \\frac{2\\times2\\times3}{4-1\\times\\left(\\frac12\\right)^2} \\\\\n&= \\frac{12}{4-\\frac14} \\\\\n&= \\frac{12}{\\frac{15}{4}} \\\\\n&= \\frac{48}{15} \\\\\n&= \\frac{16}{5}.\n\\end{aligned}"
          },
          {
            "text": "理由： 直接计算即得。"
          },
          {
            "text": "第三步（给出结论）：\n所以"
          },
          {
            "latex": "|AB|=\\frac{16}{5}"
          },
          {
            "text": "。\n理由： 根据计算得到最终答案。\n关键结论："
          },
          {
            "latex": "|AB| = \\frac{16}{5}"
          },
          {
            "text": "例 2（稍变形）\n题目： 已知椭圆"
          },
          {
            "latex": "\\frac{x^2}{4}+\\frac{y^2}{3}=1"
          },
          {
            "text": "，过右焦点且倾斜角为"
          },
          {
            "latex": "\\theta"
          },
          {
            "text": "的焦点弦长等于"
          },
          {
            "latex": "\\frac{16}{5}"
          },
          {
            "text": "，求"
          },
          {
            "latex": "\\cos\\theta"
          },
          {
            "text": "的值。\n解题步骤："
          },
          {
            "text": "第一步（代入公式）：\n由公式"
          },
          {
            "latex": "L=\\frac{2ab^2}{a^2-c^2\\cos^2\\theta}"
          },
          {
            "text": "，得"
          },
          {
            "latex": "\\frac{16}{5} = \\frac{12}{4-\\cos^2\\theta}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "。\n理由： 已知"
              },
              {
                "type": "math",
                "latex": "a=2,b^2=3,c=1"
              },
              {
                "type": "text",
                "text": "，代入化简。"
              }
            ]
          },
          {
            "text": "第二步（解方程）：\n分母乘过去："
          },
          {
            "latex": "\\begin{aligned}\n16(4-\\cos^2\\theta) &= 60 \\\\\n64 - 16\\cos^2\\theta &= 60 \\\\\n16\\cos^2\\theta &= 4 \\\\\n\\cos^2\\theta &= \\frac14 \\\\\n\\cos\\theta &= \\pm\\frac12.\n\\end{aligned}"
          },
          {
            "text": "理由： 代数变形解出"
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "text": "，注意开方有正负。"
          },
          {
            "text": "第三步（结论）：\n所以"
          },
          {
            "latex": "\\cos\\theta = \\pm\\frac12"
          },
          {
            "text": "。\n理由： 倾斜角"
          },
          {
            "latex": "\\theta"
          },
          {
            "text": "范围"
          },
          {
            "latex": "[0,\\pi)"
          },
          {
            "text": "，余弦可正可负，均能使弦长成立。\n关键结论："
          },
          {
            "latex": "\\cos\\theta = \\pm\\frac12"
          },
          {
            "text": "例 3（综合应用）\n题目： 已知椭圆"
          },
          {
            "latex": "\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "（"
              },
              {
                "type": "math",
                "latex": "a>b>0"
              },
              {
                "type": "text",
                "text": "）的离心率"
              }
            ]
          },
          {
            "latex": "e=\\frac12"
          },
          {
            "text": "，过右焦点且倾斜角为"
          },
          {
            "latex": "60^\\circ"
          },
          {
            "text": "的直线被椭圆截得的弦长等于"
          },
          {
            "latex": "\\frac{16}{5}"
          },
          {
            "text": "，求椭圆方程。\n解题步骤："
          },
          {
            "text": "第一步（利用离心率）：\n由"
          },
          {
            "latex": "e=\\frac{c}{a}=\\frac12"
          },
          {
            "text": "得"
          },
          {
            "latex": "c=\\frac a2"
          },
          {
            "text": "，从而"
          },
          {
            "latex": "b^2=a^2-c^2=a^2-\\frac{a^2}{4}=\\frac{3a^2}{4}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "。\n理由： 离心率给出"
              },
              {
                "type": "math",
                "latex": "a,b,c"
              },
              {
                "type": "text",
                "text": "的关系。"
              }
            ]
          },
          {
            "text": "第二步（代入弦长公式）："
          },
          {
            "latex": "\\theta=60^\\circ"
          },
          {
            "text": "，"
          },
          {
            "latex": "\\cos\\theta=\\frac12"
          },
          {
            "text": "，代入公式"
          },
          {
            "latex": "L=\\frac{2ab^2}{a^2-c^2\\cos^2\\theta}"
          },
          {
            "text": "得"
          },
          {
            "latex": "\\begin{aligned}\nL &= \\frac{2a\\cdot\\frac{3a^2}{4}}{a^2-\\frac{a^2}{4}\\cdot\\frac14} \\\\\n&= \\frac{\\frac{3a^3}{2}}{a^2-\\frac{a^2}{16}} \\\\\n&= \\frac{\\frac{3a^3}{2}}{\\frac{15a^2}{16}} \\\\\n&= \\frac{3a^3}{2}\\cdot\\frac{16}{15a^2} \\\\\n&= \\frac{8a}{5}.\n\\end{aligned}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "理由： 利用"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "表达"
              },
              {
                "type": "math",
                "latex": "L"
              },
              {
                "type": "text",
                "text": "，化简为"
              },
              {
                "type": "math",
                "latex": "8a/5"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "第三步（求 ）：\n令"
          },
          {
            "latex": "\\frac{8a}{5}=\\frac{16}{5}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，解得"
              },
              {
                "type": "math",
                "latex": "a=2"
              },
              {
                "type": "text",
                "text": "。于是"
              },
              {
                "type": "math",
                "latex": "c=1"
              },
              {
                "type": "text",
                "text": "，"
              },
              {
                "type": "math",
                "latex": "b^2=3"
              },
              {
                "type": "text",
                "text": "。\n理由： 由待定系数法求出"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "，再回代得"
              },
              {
                "type": "math",
                "latex": "b"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "第四步（结论）：\n椭圆方程为"
          },
          {
            "latex": "\\frac{x^2}{4}+\\frac{y^2}{3}=1"
          },
          {
            "text": "。\n理由： 代入标准形式即得。\n关键结论："
          },
          {
            "latex": "\\frac{x^2}{4}+\\frac{y^2}{3}=1"
          }
        ]
      },
      {
        "key": "traps",
        "title": "易错提醒",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点一（条件遗漏）\n使用公式时未验证椭圆是否满足焦点在"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴的标准形式，以及直线是否确实过焦点。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解（条件验证）：\n公式仅适用于焦点在"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴上的椭圆，且直线过该焦点；若焦点在"
              },
              {
                "type": "math",
                "latex": "y"
              },
              {
                "type": "text",
                "text": "轴或直线不过焦点，公式不成立。"
              }
            ]
          },
          {
            "text": "错因分析（忽视前提）：\n学生看到“弦长”“椭圆”等关键字就机械套用公式，忽略公式的适用前提。"
          },
          {
            "text": "易错点二（平方漏写）\n将公式分母误写为"
          },
          {
            "latex": "a^2-c^2\\cos\\theta"
          },
          {
            "text": "，缺少"
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "text": "中的平方。"
          },
          {
            "text": "正确理解（平方形式）：\n分母中的"
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "来源于参数"
              },
              {
                "type": "math",
                "latex": "t"
              },
              {
                "type": "text",
                "text": "系数中的"
              }
            ]
          },
          {
            "latex": "\\cos\\theta"
          },
          {
            "text": "平方，且平方后保证了分母非负。"
          },
          {
            "text": "错因分析（平方缺失）：\n学生平时用"
          },
          {
            "latex": "\\cos\\theta"
          },
          {
            "text": "表示方向向量时常忘记平方，导致符号错误。"
          },
          {
            "text": "易错点三（通径记反）\n将通径长记作"
          },
          {
            "latex": "\\frac{2a^2}{b}"
          },
          {
            "text": "或"
          },
          {
            "latex": "\\frac{2a}{b^2}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，混淆"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "与"
              },
              {
                "type": "math",
                "latex": "b"
              },
              {
                "type": "text",
                "text": "的位置。"
              }
            ]
          },
          {
            "text": "正确理解（通径推导）：\n由公式当"
          },
          {
            "latex": "\\theta=90^\\circ"
          },
          {
            "text": "时得"
          },
          {
            "latex": "L=\\frac{2b^2}{a}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，也可从几何意义：通径是过焦点垂直于长轴的弦，长为"
              },
              {
                "type": "math",
                "latex": "2b^2/a"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "错因分析（记忆混淆）：\n学生未从推导记忆，仅靠机械记忆，导致"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "、"
              },
              {
                "type": "math",
                "latex": "b"
              },
              {
                "type": "text",
                "text": "位置颠倒。"
              }
            ]
          }
        ]
      },
      {
        "key": "summary",
        "title": "复盘总结",
        "layout": "text",
        "items": [
          {
            "text": "一句话核心\n焦点弦长公式：已知倾斜角直接求过焦点的弦长，避免联立方程组。"
          },
          {
            "text": "使用条件"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "条件 1（椭圆标准）： 焦点在"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴上的椭圆，"
              },
              {
                "type": "math",
                "latex": "a>b>0"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "条件 2（直线条件）： 弦过椭圆焦点，且倾斜角"
          },
          {
            "latex": "\\theta"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "为直线与"
              },
              {
                "type": "math",
                "latex": "x"
              },
              {
                "type": "text",
                "text": "轴正方向夹角。"
              }
            ]
          },
          {
            "text": "关键提醒"
          },
          {
            "text": "易错点（公式前提）： 检查椭圆焦点位置和直线是否过焦点；分母是"
          },
          {
            "latex": "a^2-c^2\\cos^2\\theta"
          },
          {
            "text": "，注意"
          },
          {
            "latex": "\\cos^2\\theta"
          },
          {
            "text": "。"
          },
          {
            "text": "检查项（通径检验）： 令"
          },
          {
            "latex": "\\theta=90^\\circ"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "得"
              },
              {
                "type": "math",
                "latex": "L=2b^2/a"
              },
              {
                "type": "text",
                "text": "，可验证公式是否正确。"
              }
            ]
          }
        ]
      }
    ]
  }
}
