/**
 * Auto-generated by scripts/build_detail_page_js.py.
 *
 * This file is for the mini-program detail page only.
 * It intentionally excludes search-only metadata such as:
 *   - search
 *   - searchmeta
 *   - ranking
 *   - pinyin / pinyinAbbr and other search keys under search.*
 *
 * Top-level export:
 *   module.exports = { [id]: DetailRecord }
 *
 * DetailRecord core fields:
 *   - id: stable content id from meta.json:id
 *   - title: display title from meta.json:core.title
 *   - display_version: currently 2, meaning structured latex-first sections are available
 *   - sections: structured display sections built from raw tex before clean_tex
 *
 * DetailRecord metadata fields:
 *   - module: Logical module name from meta.json; source=module; why=Lets the detail page know the business module without using the directory name.
 *   - alias: Alternative titles or aliases; source=core.alias; why=Useful for secondary display, FAQ labels, or future content hints.
 *   - difficulty: Difficulty level; source=core.difficulty; why=Supports badges, filtering, or display of expected problem difficulty.
 *   - category: Primary topic category; source=core.category; why=Supports detail-page labeling and page-level context.
 *   - tags: Topic tags; source=core.tags; why=Useful for related content chips and page-level navigation.
 *   - core_summary: Short summary from core metadata; source=core.summary; why=Keeps a compact summary separate from the long cleaned `summary` field.
 *   - core_formula: Primary formula or theorem statement; source=math.core_formula; why=Usually the first math block the detail page wants to highlight.
 *   - related_formulas: Closely related formulas; source=math.related_formulas; why=Supports extended reading and future expandable formula panels.
 *   - variables: Variables used by the formula; source=math.variables; why=Helps the detail page explain notation without re-parsing the formula text.
 *     variables shape: [{ latex, description? }] so the front end can render variables as math.
 *   - conditions: Conditions under which the statement holds; source=math.conditions; why=Important guardrails for the detail page so conditions are easy to show.
 *   - conclusions: Main conclusion or equality case; source=math.conclusions; why=Lets the page show the takeaway without re-reading the full proof.
 *   - usage: Usage scenarios and problem types; source=usage; why=Supports 'when to use this' sections on the detail page.
 *   - interactive: Interactive page configuration; source=interactive; why=Keeps detail-page interactive affordances close to the content record.
 *   - assets: Static asset references; source=assets; why=The detail page can directly load svg, png, mp4, or other resources.
 *   - shareConfig: Share card title and description; source=shareConfig; why=Used directly by the mini-program sharing entry points.
 *   - relations: Prerequisites and related content; source=relations; why=Supports related-content blocks and learning-path navigation.
 *   - isPro: Premium or gated flag; source=isPro; why=Allows the page to show lock states or access messaging.
 *   - remarks: Free-form remarks; source=remarks; why=Keeps room for editorial notes without changing the schema.
 *   - knowledgeNode: Primary knowledge-tree node; source=knowledgeNode; why=Useful for breadcrumb-like display or curriculum linking.
 *   - altNodes: Alternative knowledge-tree nodes; source=altNodes; why=Supports cross-linking when one topic belongs to multiple paths.
 *
 * DetailRecord cleaned text fields:
 *   - statement: Main cleaned theorem/problem statement; source=01_statement.tex; fallback=content.statement; why=This is the primary content block shown at the top of the detail page.
 *   - explanation: Cleaned explanatory text; source=02_explanation.tex; fallback=none; why=Used for intuition, decomposition, and interpretation under the statement.
 *   - proof: Cleaned proof text; source=03_proof.tex; fallback=none; why=Keeps the formal derivation in display-ready plain text.
 *   - examples: Cleaned examples text; source=04_examples.tex; fallback=none; why=Supports worked examples or application snippets on the detail page.
 *   - traps: Cleaned common pitfalls text; source=05_traps.tex; fallback=content.common_tricks; why=Useful for mistake reminders and learning notes.
 *   - summary: Cleaned summary text; source=06_summary.tex; fallback=core.summary; why=Provides a concise end-of-page takeaway for quick review.
 *
 * Structured sections schema:
 *   - Section = { key, title, layout, items }
 *   - Supported item forms:
 *     1. { text: string }
 *     2. { latex: string }
 *     3. { segments: [{ type: 'text', text } | { type: 'math', latex }] }
 *     4. theorem-list item: { title, segments }
 *   - Rich parser rules for mixed text/math sections:
 *     - Long equation-chain math is promoted to standalone { latex } items.
 *     - Trailing punctuation is stripped out of latex and kept in text segments.
 *     - This improves canonical migration to math_block and avoids inline overflow.
 *   - Important layouts used by this builder:
 *     - text
 *     - theorem-list
 *   - Legacy plain-text fields remain in the record for compatibility and debugging.
 */
module.exports = {
  "F028": {
    "id": "F028",
    "title": "周期与对称性连锁性质",
    "module": "function",
    "alias": [
      "周期对称轴连锁",
      "半周期复制对称性",
      "两轴推出周期"
    ],
    "difficulty": 3,
    "category": "函数性质",
    "tags": [
      "函数周期性",
      "对称性",
      "抽象函数",
      "对称轴",
      "对称中心",
      "最小正周期"
    ],
    "core_summary": "若T是函数的一个周期，则一条对称轴或一个对称中心可按T/2向左右连锁；两条不同对称轴间距的两倍是函数的一个正周期。若T0为最小正周期，则可由一条对称轴完整刻画全部对称轴。",
    "core_formula": "\\begin{array}{@{}l@{}}\\displaystyle x=a+\\frac{kT}{2}\\quad(k\\in\\mathbb{Z}),\\\\\\displaystyle \\left(b+\\frac{kT}{2},\\,c\\right)\\quad(k\\in\\mathbb{Z}),\\\\\\displaystyle P=2|a_1-a_2|.\\end{array}",
    "related_formulas": "x=a+\\frac{kT_0}{2}\\quad(k\\in\\mathbb{Z})",
    "variables": [
      {
        "latex": "f"
      },
      {
        "latex": "x"
      },
      {
        "latex": "T"
      },
      {
        "latex": "T_0"
      },
      {
        "latex": "P"
      },
      {
        "latex": "a"
      },
      {
        "latex": "b"
      },
      {
        "latex": "c"
      },
      {
        "latex": "k"
      },
      {
        "latex": "a_1"
      },
      {
        "latex": "a_2"
      },
      {
        "latex": "s"
      }
    ],
    "conditions": [
      "函数$f(x)$定义在$\\mathbb{R}$上，且$T>0$是$f$的一个周期，即$f(x+T)=f(x)$对所有$x\\in\\mathbb{R}$成立。",
      "函数$f(x)$有一条对称轴$x=a$，即$f(a+x)=f(a-x)$；或有一个对称中心$(b,c)$，即$f(b+x)+f(b-x)=2c$。",
      "若需完整刻画全部对称轴，则进一步假设$T_0$是函数的最小正周期。"
    ],
    "conclusions": [
      "若$T$是一个周期且$x=a$是一条对称轴，则$x=a+\\dfrac{kT}{2}$（$k\\in\\mathbb{Z}$）均为对称轴。",
      "若$T$是一个周期且$(b,c)$是一个对称中心，则$\\left(b+\\dfrac{kT}{2},c\\right)$（$k\\in\\mathbb{Z}$）均为对称中心。",
      "若$f$有两条不同的对称轴$x=a_1$和$x=a_2$，则$2|a_1-a_2|$是$f$的一个正周期，但不一定是最小正周期。",
      "若$T_0$是$f$的最小正周期且$x=a$是一条对称轴，则$f$的全部对称轴恰为$x=a+\\dfrac{kT_0}{2}$（$k\\in\\mathbb{Z}$）。",
      "在一般抽象函数框架下，不应把最小正周期下对称轴的完整刻画无条件照搬到全部对称中心。"
    ],
    "usage": {
      "scenarios": [
        "抽象函数性质题",
        "周期性与对称性综合题",
        "压轴题条件转化",
        "最小正周期判断"
      ],
      "problem_types": [
        "填空题",
        "证明题",
        "选择题"
      ],
      "exam_frequency": 0.8,
      "exam_score": 6
    },
    "interactive": {
      "has_diagram": true,
      "geogebra_id": "",
      "param_demo": {
        "T": 4,
        "a": 1,
        "b": "\\frac{\\pi}{6}",
        "c": 3
      }
    },
    "assets": {
      "svg": "F028.svg"
    },
    "shareConfig": {
      "title": "周期与对称性连锁：半周期连接同类对称位置",
      "shareDesc": "已知一个周期和一条对称轴或一个对称中心，可以按半周期推出一组新的同类对称位置；已知两条对称轴，可以得到一个等于两倍轴间距的周期。注意区分一个周期与最小正周期。"
    },
    "relations": {
      "prerequisites": [
        "周期函数定义",
        "最小正周期定义",
        "对称轴定义",
        "对称中心定义"
      ],
      "related_ids": [],
      "similar": "周期函数的一条对称轴或一个对称中心可按半周期连锁；两条不同对称轴可推出一个等于两倍轴间距的周期。若要完整刻画全部对称轴，需要使用最小正周期。"
    },
    "isPro": 0,
    "remarks": "已统一修正：普通周期只能推出一组对称轴或对称中心；两条对称轴只能推出一个周期而非最小正周期；补充最小正周期下全部对称轴的完整证明；明确T/2是对称位置的间隔但不一定是函数周期；避免把对称轴的全部刻画无条件照搬到全部对称中心。",
    "knowledgeNode": "函数-性质-周期性与对称性",
    "altNodes": "函数-性质-对称性",
    "statement": "条件\n- 周期条件：\n函数 f(x) 定义在 R 上，且 T>0 是 f 的一个周期，即\nf(x+T)=f(x),\nx in R.\n- 对称轴条件：\n若直线 x=a 是函数 y=f(x) 图像的一条对称轴，则\nf(a+x)=f(a-x),\nx in R.\n- 对称中心条件：\n若点 (b,c) 是函数 y=f(x) 图像的一个对称中心，则\nf(b+x)+f(b-x)=2c,\nx in R.\n结论\n- 结论一（对称轴连锁）：\n若 x=a 是函数图像的一条对称轴，则对任意 k in Z，\nx=a+(kT) / (2)\n也都是函数图像的对称轴。\n- 结论二（对称中心连锁）：\n若 (b,c) 是函数图像的一个对称中心，则对任意 k in Z，\n(\nb+(kT) / (2),\n\\,c\n)\n也都是函数图像的对称中心。\n- 结论三（两条对称轴推出周期）：\n若 x=a_1 与 x=a_2 是函数图像的两条不同对称轴，则\nP=2|a_1-a_2|\n是函数 f 的一个正周期。\n但由此不能直接断定 P 是函数的最小正周期。\n- 结论四（最小正周期下的全部对称轴）：\n若 T_0 是函数 f 的最小正周期，且 x=a 是函数图像的一条对称轴，则函数图像的全部对称轴恰为\nx=a+(kT_0) / (2),\nk in Z.\n重要说明\n如果题目只说明 T 是函数的一个周期，而没有说明 T 是最小正周期，那么\nx=a+(kT) / (2)\n与\n(\nb+(kT) / (2),\n\\,c\n)\n只表示由已知条件必然能够推出的一组对称轴或一组对称中心，不能直接称为函数图像的全部对称轴或全部对称中心。\n此外，上述“全部刻画”结论只针对对称轴。对于一般抽象函数，即使已知最小正周期和一个对称中心，也不应在没有其他条件时直接断言上述点列包含全部对称中心。",
    "explanation": "一句话直觉\n周期与对称性叠加后，同类对称位置会按已知周期的一半向左右连锁出现。\n核心拆解\n- 要点一（周期定义）：\nf(x+T)=f(x) 对任意 x in R 成立。\n- 要点二（对称轴定义）：\nf(a+x)=f(a-x) 对任意 x in R 成立。\n- 要点三（对称轴连锁）：\n由周期性与对称轴定义可推出\nf(a+(T) / (2)+x)\n=\nf(a+(T) / (2)-x),\n因此 x=a+T/2 也是对称轴。反复应用后可得到\nx=a+(kT) / (2),\nk in Z,\n这一组必然存在的对称轴。\n- 要点四（对称中心连锁）：\n若 (b,c) 是对称中心，则同理有\nf(b+(T) / (2)+x)\n+\nf(b+(T) / (2)-x)\n=2c,\n所以 (b+T/2,c) 仍是对称中心。\n几何本质（镜像与平移）\n周期表示图像水平平移 T 后与原图像重合；对称轴表示关于某条竖直直线镜像后图像不变。把“平移一个周期”和“关于已知轴反射”组合起来，会得到关于相距 T/2 的新直线反射，因此同类对称位置每隔 T/2 再次出现。\n两次关于平行直线的轴对称，等价于一次水平平移，且平移量等于两条直线间距的两倍。这就是“两条对称轴推出一个周期”的几何原因。\n代数意义（等式推导）\n以对称轴为例，直接计算：\nf(a+(T) / (2)+x)\n& =f(a-(T) / (2)+x)\n& & （相差一个周期 T） \\\\\n& =f(a+(x-(T) / (2))) \\\\\n& =f(a-(x-(T) / (2)))\n& & （关于 x=a 对称） \\\\\n& =f(a+(T) / (2)-x).\n这正是直线 x=a+T/2 为对称轴的判定式。\n考点价值（快速转化）\n- 考法一（求一组对称轴）： 已知一个周期和一条对称轴，写出 x=a+kT/2。\n- 考法二（求全部对称轴）： 只有进一步知道 T_0 是最小正周期时，才能写成 x=a+kT_0/2 的全部形式。\n- 考法三（求一个周期）： 已知两条不同对称轴，计算 P=2|a_1-a_2|；所得 P 不一定是最小正周期。\n顿悟点\n半个已知周期控制同类对称位置的连锁，两倍轴间距产生一个周期；但“一个周期”不能自动升级为“最小正周期”。\n使用场景\n- 场景一（抽象函数）： 将周期条件与对称条件互相转化，用于求值、证明周期性或排除错误选项。\n- 场景二（三角函数）： 结合最小正周期、最值点和对称轴确定相位参数或验证函数图像性质。",
    "proof": "思路提示\n把周期、对称轴和对称中心都写成对任意实数成立的恒等式，再通过代换与复合对称推出新的对称性和周期性。\n正式推导\n- 步骤一（对称轴连锁）：\n设 T>0 是 f 的一个周期，且 x=a 是一条对称轴。下面证明 x=a+T/2 也是对称轴。\nf(a+(T) / (2)+x)\n& =f(a-(T) / (2)+x)\n& & （两自变量相差 T） \\\\\n& =f(a+(x-(T) / (2))) \\\\\n& =f(a-(x-(T) / (2)))\n& & （关于 x=a 对称） \\\\\n& =f(a+(T) / (2)-x).\n该等式对任意 x in R 成立，因此 x=a+T/2 是一条对称轴。\n把同一结论反复向右或向左应用，可得\nx=a+(kT) / (2),\nk in Z,\n均为对称轴。\n- 步骤二（对称中心连锁）：\n设 (b,c) 是 f 的一个对称中心。令\ng(x)=f(x+b)-c.\n则 g 以 T 为一个周期，并且\ng(-x)=-g(x),\n即 g 是奇函数。下面证明点 (T/2,0) 是 g 图像的一个对称中心：\ng((T) / (2)+x)\n& =g(-(T) / (2)+x)\n& & （两自变量相差 T） \\\\\n& =g(-((T) / (2)-x)) \\\\\n& =-g((T) / (2)-x)\n& & （g 为奇函数）.\n所以\ng((T) / (2)+x)\n+\ng((T) / (2)-x)\n=0.\n代回 g(x)=f(x+b)-c，得到\nf(b+(T) / (2)+x)\n+\nf(b+(T) / (2)-x)\n=2c.\n因此 (b+T/2,c) 是 f 图像的一个对称中心。反复应用可得\n(b+(kT) / (2),c),\nk in Z,\n均为对称中心。这里得到的是一组必然存在的对称中心，不能在没有其他条件时称为全部对称中心。\n- 步骤三（两条对称轴推出一个周期）：\n设 x=a_1 和 x=a_2 是两条不同的对称轴。由对称轴定义，对任意 u in R，\nf(u)=f(2a_1-u).\n再关于直线 x=a_2 对称，得到\nf(u)\n& =f(2a_1-u) \\\\\n& =f(2a_2-(2a_1-u)) \\\\\n& =f(u+2(a_2-a_1)).\n因此 2(a_2-a_1) 是 f 的一个非零周期。周期取相反数后仍是周期，所以\nP=2|a_1-a_2|\n是 f 的一个正周期，但不一定是最小正周期。\n- 步骤四（最小正周期下刻画全部对称轴）：\n进一步设 T_0 是 f 的最小正周期，且 x=a 是一条对称轴。\n由步骤一可知，\nx=a+(kT_0) / (2),\nk in Z,\n均为对称轴。\n反过来，设 x=s 是任意一条对称轴。若 s=a，结论显然成立；若 s a，由步骤三可知\nP=2|s-a|\n是一个正周期。\n对 P 作带余除法：\nP=nT_0+r,\nn in Z_ 0,\n0 r<T_0.\n由于两个周期之差仍是周期，r=P-nT_0 也是周期。由 T_0 的最小正性，只能有 r=0。因此\n2|s-a|=nT_0.\n于是存在 k in Z，使得\ns=a+(kT_0) / (2).\n故函数图像的全部对称轴恰为\nx=a+(kT_0) / (2),\nk in Z.\n结论回扣\n一个已知周期能生成一组间隔为 T/2 的同类对称位置；两条不同对称轴能生成一个等于两倍轴间距的周期；使用最小正周期时，才能进一步完整刻画全部对称轴。",
    "examples": "例 1（由一个周期推出一组对称轴）\n题目：\n设定义在 R 上的函数 f(x) 以 4 为一个周期，且 x=1 是它的一条对称轴。写出由这些条件必然能够推出的一组对称轴。\n解题步骤：\n- 第一步（提取条件）：\n已知\nT=4,\na=1.\n- 第二步（应用连锁结论）：\n由\nx=a+(kT) / (2),\nk in Z,\n得\nx=1+(4k) / (2)=1+2k,\nk in Z.\n- 第三步（辨析结论范围）：\n因为题目只说 4 是一个周期，没有说明它是最小正周期，所以只能说\nx=1+2k,\nk in Z,\n是一组必然存在的对称轴，不能断言它们就是全部对称轴。\n关键结论：\nx=1+2k, k in Z\n均为对称轴。\n例 2（对称中心连锁）\n题目：\n若函数 f(x) 在 R 上以 为一个周期，且关于点\n(( ) / (6),3)\n中心对称，写出由这些条件必然能够推出的一组对称中心。\n解题步骤：\n- 第一步（提取条件）：\nT= ,\n(b,c)=(( ) / (6),3).\n- 第二步（应用连锁结论）：\n由\n(b+(kT) / (2),\\,c),\nk in Z,\n代入可得\n(\n( ) / (6)+(k ) / (2),\n\\,3\n),\nk in Z.\n- 第三步（辨析结论范围）：\n题目只给出一个周期 ，所以这里得到的是一组必然存在的对称中心，不应直接称为全部对称中心。\n关键结论：\n(\n( ) / (6)+(k ) / (2),\n\\,3\n),\nk in Z\n均为对称中心。\n例 3（两条对称轴推出一个周期）\n题目：\n已知定义在 R 上的函数 f(x) 有两条不同的对称轴\nx=-1\n和\nx=3.\n证明 f 是周期函数，并求出它的一个正周期。\n解题步骤：\n- 第一步（计算轴间距）：\n|3-(-1)|=4.\n- 第二步（两倍间距得到周期）：\nP=2 * 4=8.\n- 第三步（直接验证）：\n由 x=-1 为对称轴，\nf(t)=f(-2-t).\n再利用 x=3 为对称轴，\nf(-2-t)\n=f (6-(-2-t) )\n=f(t+8).\n因此\nf(t+8)=f(t)\n对任意 t in R 成立。\n关键结论：\n8 是 f 的一个正周期\n但不能仅凭这两条对称轴断定 8 是最小正周期。\n例 4（为什么不能轻易写“全部”）\n题目：\n函数\nf(x)= x\n以 4 为一个周期，且 x=0 是一条对称轴。\n利用连锁结论可以推出哪些对称轴？这些是否为全部对称轴？\n解答：\n由 T=4 、a=0，可推出\nx=0+(k * 4 ) / (2)\n=2k ,\nk in Z,\n均为对称轴。\n但 x 的最小正周期是 2 ，它的全部对称轴为\nx=k ,\nk in Z.\n因此，用一个非最小正周期得到的只是部分对称轴，不能写成全部对称轴。\n例 5（最小正周期下确定全部对称轴）\n题目：\n设 T_0=6 是函数 f 的最小正周期，且 x=1 是函数图像的一条对称轴。求函数图像的全部对称轴。\n解答：\n由最小正周期下的完整结论，全部对称轴恰为\nx=1+(kT_0) / (2)\n=1+3k,\nk in Z.\n关键结论：\nx=1+3k, k in Z\n是函数图像的全部对称轴。",
    "traps": "- 易错点一（把“一组”误写成“全部”）：\n已知 T 是函数的一个周期，就直接说全部对称轴为\nx=a+(kT) / (2).\n- 正确理解：\n当 T 只是一个周期时，\nx=a+(kT) / (2)\n仅表示由已知条件必然推出的一组对称轴。\n若进一步知道 T_0 是最小正周期，则全部对称轴恰为\nx=a+(kT_0) / (2),\nk in Z.\n- 反例：\n函数\nf(x)= x\n以 4 为一个周期。\n取对称轴 x=0，公式只给出\nx=2k ,\n但实际还有\nx=(2k+1) .\n- 易错点二（把半周期写成整周期）：\n误写成\nx=a+kT.\n- 正确理解：\n同类对称轴的位置每隔 T/2 必然再次出现，因此应写成\nx=a+(kT) / (2),\nk in Z.\n注意：这并不表示 T/2 本身一定是函数的周期。\n- 易错点三（对称中心纵坐标也跟着变化）：\n误写为\n(\nb+(kT) / (2),\n\\,c+(kT) / (2)\n).\n- 正确理解：\n这里只改变对称中心的横坐标，纵坐标保持为 c，应写为\n(\nb+(kT) / (2),\n\\,c\n).\n- 易错点四（把两条对称轴的间距直接当周期）：\n误认为周期为\n|a_1-a_2|.\n- 正确理解：\n两次关于平行直线的轴对称合成为一次平移，平移量是轴间距的两倍，所以\n2|a_1-a_2|\n是函数的一个周期。\n- 易错点五（把推出的周期当作最小正周期）：\n由两条对称轴得到\n2|a_1-a_2|\n后，直接称其为最小正周期。\n- 正确理解：\n该数只能保证是函数的一个正周期。\n它是否为最小正周期，还需要结合函数的其他条件进一步判断。\n- 易错点六（把对称轴的“全部刻画”照搬给对称中心）：\n看到最小正周期 T_0 和一个对称中心 (b,c)，就无条件断言全部对称中心为\n(b+(kT_0) / (2),c).\n- 正确理解：\n在当前只假设函数定义于 R 的一般抽象框架下，上式只能保证给出一组对称中心。若要断言它们是全部对称中心，还需要题目提供适当的附加条件。",
    "summary": "一句话核心\n一个已知周期可以把对称轴或对称中心按半周期向左右连锁；两条不同的对称轴则能推出一个等于两倍轴间距的周期。\n核心公式\n- 若 T 是函数的一个周期，x=a 是一条对称轴，则\nx=a+(kT) / (2),\nk in Z,\n均为对称轴。\n- 若 T 是函数的一个周期，(b,c) 是一个对称中心，则\n(\nb+(kT) / (2),\n\\,c\n),\nk in Z,\n均为对称中心。\n- 若 x=a_1、x=a_2 是两条不同的对称轴，则\nP=2|a_1-a_2|\n是函数的一个正周期。\n最重要的限定\n- T 只是“一个周期”时，前两个公式给出的是一组必然存在的对称轴或对称中心，不能轻易写成“全部”。\n- 若 T_0 是最小正周期，且已知一条对称轴 x=a，则全部对称轴恰为\nx=a+(kT_0) / (2),\nk in Z.\n- 由两条对称轴推出的\n2|a_1-a_2|\n是一个周期，但不一定是最小正周期。\n- “对称位置每隔 T/2 出现”不等于“T/2 是函数的周期”。\n- 对称轴在最小正周期条件下可以完整刻画；对一般抽象函数的全部对称中心，不应在没有附加条件时直接类推。\n记忆口诀\n半周期连锁对称，两倍轴距产生周期\n同时牢记：\n一个周期 最小正周期",
    "display_version": 2,
    "sections": [
      {
        "key": "core_formula",
        "title": "核心公式",
        "layout": "text",
        "items": [
          {
            "latex": "\\begin{array}{@{}l@{}}\\displaystyle x=a+\\frac{kT}{2}\\quad(k\\in\\mathbb{Z}),\\\\\\displaystyle \\left(b+\\frac{kT}{2},\\,c\\right)\\quad(k\\in\\mathbb{Z}),\\\\\\displaystyle P=2|a_1-a_2|.\\end{array}"
          }
        ]
      },
      {
        "key": "variables",
        "title": "涉及变量",
        "layout": "text",
        "items": [
          {
            "latex": "f"
          },
          {
            "latex": "x"
          },
          {
            "latex": "T"
          },
          {
            "latex": "T_0"
          },
          {
            "latex": "P"
          },
          {
            "latex": "a"
          },
          {
            "latex": "b"
          },
          {
            "latex": "c"
          },
          {
            "latex": "k"
          },
          {
            "latex": "a_1"
          },
          {
            "latex": "a_2"
          },
          {
            "latex": "s"
          }
        ]
      },
      {
        "key": "statement",
        "title": "命题表述",
        "layout": "theorem-list",
        "items": [
          {
            "title": "周期条件：",
            "segments": [
              {
                "type": "text",
                "text": "函数"
              },
              {
                "type": "math",
                "latex": "f(x)"
              },
              {
                "type": "text",
                "text": "定义在"
              },
              {
                "type": "math",
                "latex": "\\mathbb{R}"
              },
              {
                "type": "text",
                "text": "上，且"
              },
              {
                "type": "math",
                "latex": "T>0"
              },
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的一个周期，即"
              },
              {
                "type": "math",
                "latex": "f(x+T)=f(x),\n\\quad \\forall x\\in\\mathbb{R}."
              }
            ]
          },
          {
            "title": "对称轴条件：",
            "segments": [
              {
                "type": "text",
                "text": "若直线"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "是函数"
              },
              {
                "type": "math",
                "latex": "y=f(x)"
              },
              {
                "type": "text",
                "text": "图像的一条对称轴，则"
              },
              {
                "type": "math",
                "latex": "f(a+x)=f(a-x),\n\\quad \\forall x\\in\\mathbb{R}."
              }
            ]
          },
          {
            "title": "对称中心条件：",
            "segments": [
              {
                "type": "text",
                "text": "若点"
              },
              {
                "type": "math",
                "latex": "(b,c)"
              },
              {
                "type": "text",
                "text": "是函数"
              },
              {
                "type": "math",
                "latex": "y=f(x)"
              },
              {
                "type": "text",
                "text": "图像的一个对称中心，则"
              },
              {
                "type": "math",
                "latex": "f(b+x)+f(b-x)=2c,\n\\quad \\forall x\\in\\mathbb{R}."
              }
            ]
          },
          {
            "title": "结论一（对称轴连锁）：",
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "是函数图像的一条对称轴，则对任意"
              },
              {
                "type": "math",
                "latex": "k\\in\\mathbb{Z}"
              },
              {
                "type": "text",
                "text": "，"
              },
              {
                "type": "math",
                "latex": "x=a+\\frac{kT}{2}"
              },
              {
                "type": "text",
                "text": "也都是函数图像的对称轴。"
              }
            ]
          },
          {
            "title": "结论二（对称中心连锁）：",
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "(b,c)"
              },
              {
                "type": "text",
                "text": "是函数图像的一个对称中心，则对任意"
              },
              {
                "type": "math",
                "latex": "k\\in\\mathbb{Z}"
              },
              {
                "type": "text",
                "text": "，"
              },
              {
                "type": "math",
                "latex": "\\left(\nb+\\frac{kT}{2},\n\\,c\n\\right)"
              },
              {
                "type": "text",
                "text": "也都是函数图像的对称中心。"
              }
            ]
          },
          {
            "title": "结论三（两条对称轴推出周期）：",
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "x=a_1"
              },
              {
                "type": "text",
                "text": "与"
              },
              {
                "type": "math",
                "latex": "x=a_2"
              },
              {
                "type": "text",
                "text": "是函数图像的两条不同对称轴，则"
              },
              {
                "type": "math",
                "latex": "P=2\\left|a_1-a_2\\right|"
              },
              {
                "type": "text",
                "text": "是函数"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的一个正周期。\n但由此不能直接断定"
              },
              {
                "type": "math",
                "latex": "P"
              },
              {
                "type": "text",
                "text": "是函数的最小正周期。"
              }
            ]
          },
          {
            "title": "结论四（最小正周期下的全部对称轴）：",
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "是函数"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的最小正周期，且"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "是函数图像的一条对称轴，则函数图像的全部对称轴恰为"
              },
              {
                "type": "math",
                "latex": "x=a+\\frac{kT_0}{2},\n\\quad k\\in\\mathbb{Z}."
              },
              {
                "type": "text",
                "text": "重要说明\n如果题目只说明"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "是函数的一个周期，而没有说明"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "是最小正周期，那么"
              },
              {
                "type": "math",
                "latex": "x=a+\\frac{kT}{2}"
              },
              {
                "type": "text",
                "text": "与"
              },
              {
                "type": "math",
                "latex": "\\left(\nb+\\frac{kT}{2},\n\\,c\n\\right)"
              },
              {
                "type": "text",
                "text": "只表示由已知条件必然能够推出的一组对称轴或一组对称中心，不能直接称为函数图像的全部对称轴或全部对称中心。\n此外，上述“全部刻画”结论只针对对称轴。对于一般抽象函数，即使已知最小正周期和一个对称中心，也不应在没有其他条件时直接断言上述点列包含全部对称中心。"
              }
            ]
          }
        ]
      },
      {
        "key": "explanation",
        "title": "理解与直觉",
        "layout": "text",
        "items": [
          {
            "text": "一句话直觉\n周期与对称性叠加后，同类对称位置会按已知周期的一半向左右连锁出现。"
          },
          {
            "text": "核心拆解"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "要点一（周期定义）："
              },
              {
                "type": "math",
                "latex": "f(x+T)=f(x)"
              },
              {
                "type": "text",
                "text": "对任意"
              }
            ]
          },
          {
            "latex": "x\\in\\mathbb{R}"
          },
          {
            "text": "成立。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "要点二（对称轴定义）："
              },
              {
                "type": "math",
                "latex": "f(a+x)=f(a-x)"
              },
              {
                "type": "text",
                "text": "对任意"
              }
            ]
          },
          {
            "latex": "x\\in\\mathbb{R}"
          },
          {
            "text": "成立。"
          },
          {
            "text": "要点三（对称轴连锁）：\n由周期性与对称轴定义可推出"
          },
          {
            "latex": "f\\left(a+\\frac{T}{2}+x\\right)\n=\nf\\left(a+\\frac{T}{2}-x\\right)"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ",因此"
              },
              {
                "type": "math",
                "latex": "x=a+T/2"
              },
              {
                "type": "text",
                "text": "也是对称轴。反复应用后可得到"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",这一组必然存在的对称轴。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "要点四（对称中心连锁）：\n若"
              },
              {
                "type": "math",
                "latex": "(b,c)"
              },
              {
                "type": "text",
                "text": "是对称中心，则同理有"
              }
            ]
          },
          {
            "latex": "f\\left(b+\\frac{T}{2}+x\\right)\n+\nf\\left(b+\\frac{T}{2}-x\\right)\n=2c"
          },
          {
            "text": ",所以"
          },
          {
            "latex": "\\left(b+T/2,c\\right)"
          },
          {
            "text": "仍是对称中心。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "几何本质（镜像与平移）\n周期表示图像水平平移"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "后与原图像重合；对称轴表示关于某条竖直直线镜像后图像不变。把“平移一个周期”和“关于已知轴反射”组合起来，会得到关于相距"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "的新直线反射，因此同类对称位置每隔"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "再次出现。\n两次关于平行直线的轴对称，等价于一次水平平移，且平移量等于两条直线间距的两倍。这就是“两条对称轴推出一个周期”的几何原因。"
              }
            ]
          },
          {
            "text": "代数意义（等式推导）\n以对称轴为例，直接计算："
          },
          {
            "latex": "\\begin{aligned}\nf\\left(a+\\frac{T}{2}+x\\right)\n& =f\\left(a-\\frac{T}{2}+x\\right)\n& & \\text{（相差一个周期 $T$）} \\\\\n& =f\\left(a+\\left(x-\\frac{T}{2}\\right)\\right) \\\\\n& =f\\left(a-\\left(x-\\frac{T}{2}\\right)\\right)\n& & \\text{（关于 $x=a$ 对称）} \\\\\n& =f\\left(a+\\frac{T}{2}-x\\right).\n\\end{aligned}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "这正是直线"
              },
              {
                "type": "math",
                "latex": "x=a+T/2"
              },
              {
                "type": "text",
                "text": "为对称轴的判定式。"
              }
            ]
          },
          {
            "text": "考点价值（快速转化）"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "考法一（求一组对称轴）： 已知一个周期和一条对称轴，写出"
              },
              {
                "type": "math",
                "latex": "x=a+kT/2"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "考法二（求全部对称轴）： 只有进一步知道"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "是最小正周期时，才能写成"
              },
              {
                "type": "math",
                "latex": "x=a+kT_0/2"
              },
              {
                "type": "text",
                "text": "的全部形式。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "考法三（求一个周期）： 已知两条不同对称轴，计算"
              },
              {
                "type": "math",
                "latex": "P=2|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "；所得"
              },
              {
                "type": "math",
                "latex": "P"
              },
              {
                "type": "text",
                "text": "不一定是最小正周期。"
              }
            ]
          },
          {
            "text": "顿悟点\n半个已知周期控制同类对称位置的连锁，两倍轴间距产生一个周期；但“一个周期”不能自动升级为“最小正周期”。"
          },
          {
            "text": "使用场景"
          },
          {
            "text": "场景一（抽象函数）： 将周期条件与对称条件互相转化，用于求值、证明周期性或排除错误选项。"
          },
          {
            "text": "场景二（三角函数）： 结合最小正周期、最值点和对称轴确定相位参数或验证函数图像性质。"
          }
        ]
      },
      {
        "key": "proof",
        "title": "证明过程",
        "layout": "text",
        "items": [
          {
            "text": "思路提示\n把周期、对称轴和对称中心都写成对任意实数成立的恒等式，再通过代换与复合对称推出新的对称性和周期性。"
          },
          {
            "text": "正式推导"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤一（对称轴连锁）：\n设"
              },
              {
                "type": "math",
                "latex": "T>0"
              },
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的一个周期，且"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "是一条对称轴。下面证明"
              },
              {
                "type": "math",
                "latex": "x=a+T/2"
              },
              {
                "type": "text",
                "text": "也是对称轴。"
              }
            ]
          },
          {
            "latex": "\\begin{aligned}\nf\\left(a+\\frac{T}{2}+x\\right)\n& =f\\left(a-\\frac{T}{2}+x\\right)\n& & \\text{（两自变量相差 $T$）} \\\\\n& =f\\left(a+\\left(x-\\frac{T}{2}\\right)\\right) \\\\\n& =f\\left(a-\\left(x-\\frac{T}{2}\\right)\\right)\n& & \\text{（关于 $x=a$ 对称）} \\\\\n& =f\\left(a+\\frac{T}{2}-x\\right).\n\\end{aligned}"
          },
          {
            "text": "该等式对任意"
          },
          {
            "latex": "x\\in\\mathbb{R}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "成立，因此"
              },
              {
                "type": "math",
                "latex": "x=a+T/2"
              },
              {
                "type": "text",
                "text": "是一条对称轴。\n把同一结论反复向右或向左应用，可得"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",均为对称轴。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤二（对称中心连锁）：\n设"
              },
              {
                "type": "math",
                "latex": "(b,c)"
              },
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的一个对称中心。令"
              },
              {
                "type": "math",
                "latex": "g(x)=f(x+b)-c"
              },
              {
                "type": "text",
                "text": ".则"
              },
              {
                "type": "math",
                "latex": "g"
              },
              {
                "type": "text",
                "text": "以"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "为一个周期，并且"
              },
              {
                "type": "math",
                "latex": "g(-x)=-g(x)"
              },
              {
                "type": "text",
                "text": ",即"
              },
              {
                "type": "math",
                "latex": "g"
              },
              {
                "type": "text",
                "text": "是奇函数。下面证明点"
              }
            ]
          },
          {
            "latex": "\\left(T/2,0\\right)"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "g"
              },
              {
                "type": "text",
                "text": "图像的一个对称中心："
              }
            ]
          },
          {
            "latex": "\\begin{aligned}\ng\\left(\\frac{T}{2}+x\\right)\n& =g\\left(-\\frac{T}{2}+x\\right)\n& & \\text{（两自变量相差 $T$）} \\\\\n& =g\\left(-\\left(\\frac{T}{2}-x\\right)\\right) \\\\\n& =-g\\left(\\frac{T}{2}-x\\right)\n& & \\text{（$g$ 为奇函数）}.\n\\end{aligned}"
          },
          {
            "text": "所以"
          },
          {
            "latex": "g\\left(\\frac{T}{2}+x\\right)\n+\ng\\left(\\frac{T}{2}-x\\right)\n=0"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".代回"
              },
              {
                "type": "math",
                "latex": "g(x)=f(x+b)-c"
              },
              {
                "type": "text",
                "text": "，得到"
              }
            ]
          },
          {
            "latex": "f\\left(b+\\frac{T}{2}+x\\right)\n+\nf\\left(b+\\frac{T}{2}-x\\right)\n=2c"
          },
          {
            "text": ".因此"
          },
          {
            "latex": "\\left(b+T/2,c\\right)"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "图像的一个对称中心。反复应用可得"
              }
            ]
          },
          {
            "latex": "\\left(b+\\frac{kT}{2},c\\right),\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",均为对称中心。这里得到的是一组必然存在的对称中心，不能在没有其他条件时称为全部对称中心。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤三（两条对称轴推出一个周期）：\n设"
              },
              {
                "type": "math",
                "latex": "x=a_1"
              },
              {
                "type": "text",
                "text": "和"
              },
              {
                "type": "math",
                "latex": "x=a_2"
              },
              {
                "type": "text",
                "text": "是两条不同的对称轴。由对称轴定义，对任意"
              }
            ]
          },
          {
            "latex": "u\\in\\mathbb{R}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，"
              },
              {
                "type": "math",
                "latex": "f(u)=f(2a_1-u)"
              },
              {
                "type": "text",
                "text": ".再关于直线"
              },
              {
                "type": "math",
                "latex": "x=a_2"
              },
              {
                "type": "text",
                "text": "对称，得到"
              }
            ]
          },
          {
            "latex": "\\begin{aligned}\nf(u)\n& =f(2a_1-u) \\\\\n& =f\\left(2a_2-(2a_1-u)\\right) \\\\\n& =f\\left(u+2(a_2-a_1)\\right).\n\\end{aligned}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "因此"
              },
              {
                "type": "math",
                "latex": "2(a_2-a_1)"
              },
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的一个非零周期。周期取相反数后仍是周期，所以"
              },
              {
                "type": "math",
                "latex": "P=2|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的一个正周期，但不一定是最小正周期。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤四（最小正周期下刻画全部对称轴）：\n进一步设"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "是"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的最小正周期，且"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "是一条对称轴。\n由步骤一可知，"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT_0}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ",均为对称轴。\n反过来，设"
              },
              {
                "type": "math",
                "latex": "x=s"
              },
              {
                "type": "text",
                "text": "是任意一条对称轴。若"
              },
              {
                "type": "math",
                "latex": "s=a"
              },
              {
                "type": "text",
                "text": "，结论显然成立；若"
              }
            ]
          },
          {
            "latex": "s\\ne a"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，由步骤三可知"
              },
              {
                "type": "math",
                "latex": "P=2|s-a|"
              },
              {
                "type": "text",
                "text": "是一个正周期。\n对"
              },
              {
                "type": "math",
                "latex": "P"
              },
              {
                "type": "text",
                "text": "作带余除法："
              }
            ]
          },
          {
            "latex": "P=nT_0+r,\n\\quad n\\in\\mathbb{Z}_{\\ge 0},\n\\quad 0\\le r<T_0"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".由于两个周期之差仍是周期，"
              },
              {
                "type": "math",
                "latex": "r=P-nT_0"
              },
              {
                "type": "text",
                "text": "也是周期。由"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "的最小正性，只能有"
              },
              {
                "type": "math",
                "latex": "r=0"
              },
              {
                "type": "text",
                "text": "。因此"
              },
              {
                "type": "math",
                "latex": "2|s-a|=nT_0"
              },
              {
                "type": "text",
                "text": ".于是存在"
              }
            ]
          },
          {
            "latex": "k\\in\\mathbb{Z}"
          },
          {
            "text": "，使得"
          },
          {
            "latex": "s=a+\\frac{kT_0}{2}"
          },
          {
            "text": ".故函数图像的全部对称轴恰为"
          },
          {
            "latex": "x=a+\\frac{kT_0}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "结论回扣\n一个已知周期能生成一组间隔为"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "的同类对称位置；两条不同对称轴能生成一个等于两倍轴间距的周期；使用最小正周期时，才能进一步完整刻画全部对称轴。"
              }
            ]
          }
        ]
      },
      {
        "key": "examples",
        "title": "例题应用",
        "layout": "text",
        "items": [
          {
            "text": "例 1（由一个周期推出一组对称轴）\n题目：\n设定义在"
          },
          {
            "latex": "\\mathbb{R}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "上的函数"
              },
              {
                "type": "math",
                "latex": "f(x)"
              },
              {
                "type": "text",
                "text": "以"
              },
              {
                "type": "math",
                "latex": "4"
              },
              {
                "type": "text",
                "text": "为一个周期，且"
              },
              {
                "type": "math",
                "latex": "x=1"
              },
              {
                "type": "text",
                "text": "是它的一条对称轴。写出由这些条件必然能够推出的一组对称轴。\n解题步骤："
              }
            ]
          },
          {
            "text": "第一步（提取条件）：\n已知"
          },
          {
            "latex": "T=4,\n\\qquad\na=1"
          },
          {
            "text": "."
          },
          {
            "text": "第二步（应用连锁结论）：\n由"
          },
          {
            "latex": "x=a+\\frac{kT}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",得"
          },
          {
            "latex": "x=1+\\frac{4k}{2}=1+2k,\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第三步（辨析结论范围）：\n因为题目只说"
              },
              {
                "type": "math",
                "latex": "4"
              },
              {
                "type": "text",
                "text": "是一个周期，没有说明它是最小正周期，所以只能说"
              }
            ]
          },
          {
            "latex": "x=1+2k,\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",是一组必然存在的对称轴，不能断言它们就是全部对称轴。\n关键结论："
          },
          {
            "latex": "\\boxed{x=1+2k,\\quad k\\in\\mathbb{Z}}"
          },
          {
            "text": "均为对称轴。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "例 2（对称中心连锁）\n题目：\n若函数"
              },
              {
                "type": "math",
                "latex": "f(x)"
              },
              {
                "type": "text",
                "text": "在"
              }
            ]
          },
          {
            "latex": "\\mathbb{R}"
          },
          {
            "text": "上以"
          },
          {
            "latex": "\\pi"
          },
          {
            "text": "为一个周期，且关于点"
          },
          {
            "latex": "\\left(\\frac{\\pi}{6},3\\right)"
          },
          {
            "text": "中心对称，写出由这些条件必然能够推出的一组对称中心。\n解题步骤："
          },
          {
            "text": "第一步（提取条件）："
          },
          {
            "latex": "T=\\pi,\n\\qquad\n(b,c)=\\left(\\frac{\\pi}{6},3\\right)"
          },
          {
            "text": "."
          },
          {
            "text": "第二步（应用连锁结论）：\n由"
          },
          {
            "latex": "\\left(b+\\frac{kT}{2},\\,c\\right),\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",代入可得"
          },
          {
            "latex": "\\left(\n\\frac{\\pi}{6}+\\frac{k\\pi}{2},\n\\,3\n\\right),\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": "."
          },
          {
            "text": "第三步（辨析结论范围）：\n题目只给出一个周期"
          },
          {
            "latex": "\\pi"
          },
          {
            "text": "，所以这里得到的是一组必然存在的对称中心，不应直接称为全部对称中心。\n关键结论："
          },
          {
            "latex": "\\boxed{\n\\left(\n\\frac{\\pi}{6}+\\frac{k\\pi}{2},\n\\,3\n\\right),\n\\quad k\\in\\mathbb{Z}\n}"
          },
          {
            "text": "均为对称中心。"
          },
          {
            "text": "例 3（两条对称轴推出一个周期）\n题目：\n已知定义在"
          },
          {
            "latex": "\\mathbb{R}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "上的函数"
              },
              {
                "type": "math",
                "latex": "f(x)"
              },
              {
                "type": "text",
                "text": "有两条不同的对称轴"
              }
            ]
          },
          {
            "latex": "x=-1\n\\quad\\text{和}\\quad\nx=3"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".证明"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "是周期函数，并求出它的一个正周期。\n解题步骤："
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第一步（计算轴间距）："
              },
              {
                "type": "math",
                "latex": "|3-(-1)|=4"
              },
              {
                "type": "text",
                "text": "."
              }
            ]
          },
          {
            "text": "第二步（两倍间距得到周期）："
          },
          {
            "latex": "P=2\\times4=8"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第三步（直接验证）：\n由"
              },
              {
                "type": "math",
                "latex": "x=-1"
              },
              {
                "type": "text",
                "text": "为对称轴，"
              },
              {
                "type": "math",
                "latex": "f(t)=f(-2-t)"
              },
              {
                "type": "text",
                "text": ".再利用"
              },
              {
                "type": "math",
                "latex": "x=3"
              },
              {
                "type": "text",
                "text": "为对称轴，"
              }
            ]
          },
          {
            "latex": "f(-2-t)\n=f\\bigl(6-(-2-t)\\bigr)\n=f(t+8)"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".因此"
              },
              {
                "type": "math",
                "latex": "f(t+8)=f(t)"
              },
              {
                "type": "text",
                "text": "对任意"
              }
            ]
          },
          {
            "latex": "t\\in\\mathbb{R}"
          },
          {
            "text": "成立。\n关键结论："
          },
          {
            "latex": "\\boxed{8\\text{ 是 }f\\text{ 的一个正周期}}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "但不能仅凭这两条对称轴断定"
              },
              {
                "type": "math",
                "latex": "8"
              },
              {
                "type": "text",
                "text": "是最小正周期。"
              }
            ]
          },
          {
            "text": "例 4（为什么不能轻易写“全部”）\n题目：\n函数"
          },
          {
            "latex": "f(x)=\\cos x"
          },
          {
            "text": "以"
          },
          {
            "latex": "4\\pi"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "为一个周期，且"
              },
              {
                "type": "math",
                "latex": "x=0"
              },
              {
                "type": "text",
                "text": "是一条对称轴。\n利用连锁结论可以推出哪些对称轴？这些是否为全部对称轴？\n解答：\n由"
              }
            ]
          },
          {
            "latex": "T=4\\pi"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "、"
              },
              {
                "type": "math",
                "latex": "a=0"
              },
              {
                "type": "text",
                "text": "，可推出"
              }
            ]
          },
          {
            "latex": "x=0+\\frac{k\\cdot4\\pi}{2}\n=2k\\pi,\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",均为对称轴。\n但"
          },
          {
            "latex": "\\cos x"
          },
          {
            "text": "的最小正周期是"
          },
          {
            "latex": "2\\pi"
          },
          {
            "text": "，它的全部对称轴为"
          },
          {
            "latex": "x=k\\pi,\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ".因此，用一个非最小正周期得到的只是部分对称轴，不能写成全部对称轴。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "例 5（最小正周期下确定全部对称轴）\n题目：\n设"
              },
              {
                "type": "math",
                "latex": "T_0=6"
              },
              {
                "type": "text",
                "text": "是函数"
              },
              {
                "type": "math",
                "latex": "f"
              },
              {
                "type": "text",
                "text": "的最小正周期，且"
              },
              {
                "type": "math",
                "latex": "x=1"
              },
              {
                "type": "text",
                "text": "是函数图像的一条对称轴。求函数图像的全部对称轴。\n解答：\n由最小正周期下的完整结论，全部对称轴恰为"
              }
            ]
          },
          {
            "latex": "x=1+\\frac{kT_0}{2}\n=1+3k,\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ".关键结论："
          },
          {
            "latex": "\\boxed{x=1+3k,\\quad k\\in\\mathbb{Z}}"
          },
          {
            "text": "是函数图像的全部对称轴。"
          }
        ]
      },
      {
        "key": "traps",
        "title": "易错提醒",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点一（把“一组”误写成“全部”）：\n已知"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "是函数的一个周期，就直接说全部对称轴为"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT}{2}"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解：\n当"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "只是一个周期时，"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT}{2}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "仅表示由已知条件必然推出的一组对称轴。\n若进一步知道"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "是最小正周期，则全部对称轴恰为"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT_0}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": "."
          },
          {
            "text": "反例：\n函数"
          },
          {
            "latex": "f(x)=\\cos x"
          },
          {
            "text": "以"
          },
          {
            "latex": "4\\pi"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "为一个周期。\n取对称轴"
              },
              {
                "type": "math",
                "latex": "x=0"
              },
              {
                "type": "text",
                "text": "，公式只给出"
              }
            ]
          },
          {
            "latex": "x=2k\\pi"
          },
          {
            "text": ",但实际还有"
          },
          {
            "latex": "x=(2k+1)\\pi"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点二（把半周期写成整周期）：\n误写成"
              },
              {
                "type": "math",
                "latex": "x=a+kT"
              },
              {
                "type": "text",
                "text": "."
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解：\n同类对称轴的位置每隔"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "必然再次出现，因此应写成"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".注意：这并不表示"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "本身一定是函数的周期。"
              }
            ]
          },
          {
            "text": "易错点三（对称中心纵坐标也跟着变化）：\n误写为"
          },
          {
            "latex": "\\left(\nb+\\frac{kT}{2},\n\\,c+\\frac{kT}{2}\n\\right)"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解：\n这里只改变对称中心的横坐标，纵坐标保持为"
              },
              {
                "type": "math",
                "latex": "c"
              },
              {
                "type": "text",
                "text": "，应写为"
              }
            ]
          },
          {
            "latex": "\\left(\nb+\\frac{kT}{2},\n\\,c\n\\right)"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点四（把两条对称轴的间距直接当周期）：\n误认为周期为"
              },
              {
                "type": "math",
                "latex": "|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "."
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解：\n两次关于平行直线的轴对称合成为一次平移，平移量是轴间距的两倍，所以"
              },
              {
                "type": "math",
                "latex": "2|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "是函数的一个周期。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点五（把推出的周期当作最小正周期）：\n由两条对称轴得到"
              },
              {
                "type": "math",
                "latex": "2|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "后，直接称其为最小正周期。"
              }
            ]
          },
          {
            "text": "正确理解：\n该数只能保证是函数的一个正周期。\n它是否为最小正周期，还需要结合函数的其他条件进一步判断。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点六（把对称轴的“全部刻画”照搬给对称中心）：\n看到最小正周期"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "和一个对称中心"
              },
              {
                "type": "math",
                "latex": "(b,c)"
              },
              {
                "type": "text",
                "text": "，就无条件断言全部对称中心为"
              }
            ]
          },
          {
            "latex": "\\left(b+\\frac{kT_0}{2},c\\right)"
          },
          {
            "text": "."
          },
          {
            "text": "正确理解：\n在当前只假设函数定义于"
          },
          {
            "latex": "\\mathbb{R}"
          },
          {
            "text": "的一般抽象框架下，上式只能保证给出一组对称中心。若要断言它们是全部对称中心，还需要题目提供适当的附加条件。"
          }
        ]
      },
      {
        "key": "summary",
        "title": "复盘总结",
        "layout": "text",
        "items": [
          {
            "text": "一句话核心\n一个已知周期可以把对称轴或对称中心按半周期向左右连锁；两条不同的对称轴则能推出一个等于两倍轴间距的周期。"
          },
          {
            "text": "核心公式"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "是函数的一个周期，"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "是一条对称轴，则"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",均为对称轴。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "是函数的一个周期，"
              },
              {
                "type": "math",
                "latex": "(b,c)"
              },
              {
                "type": "text",
                "text": "是一个对称中心，则"
              }
            ]
          },
          {
            "latex": "\\left(\nb+\\frac{kT}{2},\n\\,c\n\\right),\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": ",均为对称中心。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "x=a_1"
              },
              {
                "type": "text",
                "text": "、"
              },
              {
                "type": "math",
                "latex": "x=a_2"
              },
              {
                "type": "text",
                "text": "是两条不同的对称轴，则"
              },
              {
                "type": "math",
                "latex": "P=2|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "是函数的一个正周期。"
              }
            ]
          },
          {
            "text": "最重要的限定"
          },
          {
            "segments": [
              {
                "type": "math",
                "latex": "T"
              },
              {
                "type": "text",
                "text": "只是“一个周期”时，前两个公式给出的是一组必然存在的对称轴或对称中心，不能轻易写成“全部”。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "若"
              },
              {
                "type": "math",
                "latex": "T_0"
              },
              {
                "type": "text",
                "text": "是最小正周期，且已知一条对称轴"
              },
              {
                "type": "math",
                "latex": "x=a"
              },
              {
                "type": "text",
                "text": "，则全部对称轴恰为"
              }
            ]
          },
          {
            "latex": "x=a+\\frac{kT_0}{2},\n\\quad k\\in\\mathbb{Z}"
          },
          {
            "text": "."
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "由两条对称轴推出的"
              },
              {
                "type": "math",
                "latex": "2|a_1-a_2|"
              },
              {
                "type": "text",
                "text": "是一个周期，但不一定是最小正周期。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "“对称位置每隔"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "出现”不等于“"
              },
              {
                "type": "math",
                "latex": "T/2"
              },
              {
                "type": "text",
                "text": "是函数的周期”。"
              }
            ]
          },
          {
            "text": "对称轴在最小正周期条件下可以完整刻画；对一般抽象函数的全部对称中心，不应在没有附加条件时直接类推。"
          },
          {
            "text": "记忆口诀"
          },
          {
            "latex": "\\boxed{\\text{半周期连锁对称，两倍轴距产生周期}}"
          },
          {
            "text": "同时牢记："
          },
          {
            "latex": "\\boxed{\\text{一个周期}\\ne\\text{最小正周期}}"
          }
        ]
      }
    ]
  }
}
