from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

INPUT_RE = re.compile(r"\\input\s*\{([^}]+)\}")
SECTION_RE = re.compile(r"\\section\s*\{(.+)\}")
SUBSECTION_RE = re.compile(r"\\subsection\s*\{(.+)\}")


def strip_comments(line: str) -> str:
    escaped = False
    for i, ch in enumerate(line):
        if ch == "\\":
            escaped = not escaped
            continue
        if ch == "%" and not escaped:
            return line[:i]
        escaped = False
    return line


def active_lines(path: Path) -> Iterable[str]:
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = strip_comments(raw).strip()
        if line:
            yield line


def normalize_tex_path(base_dir: Path, project_root: Path, input_path: str) -> Path:
    normalized = input_path.replace("\\", "/")
    if not normalized.lower().endswith(".tex"):
        normalized = f"{normalized}.tex"
    candidate_from_base = (base_dir / normalized).resolve()
    candidate_from_root = (project_root / normalized).resolve()
    if candidate_from_base.exists():
        return candidate_from_base
    if candidate_from_root.exists():
        return candidate_from_root
    return candidate_from_base


def extract_first_title(path: Path, pattern: re.Pattern[str]) -> Optional[str]:
    for line in active_lines(path):
        match = pattern.search(line)
        if match:
            return match.group(1).strip()
    return None


def parse_index_file(index_path: Path, project_root: Path) -> Tuple[List[str], List[str]]:
    sections: List[str] = []
    subsections: List[str] = []

    for line in active_lines(index_path):
        section_match = SECTION_RE.search(line)
        if section_match:
            sections.append(section_match.group(1).strip())

        for input_match in INPUT_RE.finditer(line):
            input_target = input_match.group(1).strip()
            if not input_target:
                continue
            main_path = normalize_tex_path(index_path.parent, project_root, input_target)
            if not main_path.exists():
                continue
            subsection = extract_first_title(main_path, SUBSECTION_RE)
            if subsection:
                subsections.append(subsection)

    return sections, subsections


def build_entries(root_main: Path) -> List[Tuple[str, str]]:
    entries: List[Tuple[str, str]] = []
    project_root = root_main.parent

    for line in active_lines(root_main):
        for input_match in INPUT_RE.finditer(line):
            input_target = input_match.group(1).strip()
            normalized_target = input_target.replace("\\", "/").lower()
            if not (
                normalized_target.endswith("/index")
                or normalized_target.endswith("/index.tex")
                or normalized_target == "index"
                or normalized_target == "index.tex"
            ):
                continue
            index_path = normalize_tex_path(root_main.parent, project_root, input_target)
            if not index_path.exists():
                continue

            sections, subsections = parse_index_file(index_path, project_root)
            for section in sections:
                entries.append(("section", section))
            for subsection in subsections:
                entries.append(("subsection", subsection))

    return entries


def write_seed(entries: List[Tuple[str, str]], output_path: Path) -> None:
    lines = ["% Auto-generated by scripts/generate_toc_seed.py"]
    for level, title in entries:
        if level == "section":
            lines.append(f"\\SeedSection{{{title}}}")
        else:
            lines.append(f"\\SeedSubsection{{{title}}}")
    lines.append("")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate TOC seed TeX from main/index/module main files."
    )
    parser.add_argument("--root", default="main.tex", help="Root main.tex path")
    parser.add_argument("--output", required=True, help="Output seed tex path")
    args = parser.parse_args()

    root_main = Path(args.root).resolve()
    output_path = Path(args.output).resolve()

    if not root_main.exists():
        print(f"[toc-seed] root file not found: {root_main}", file=sys.stderr)
        return 1

    entries = build_entries(root_main)
    if not entries:
        print("[toc-seed] no TOC entries found from source files", file=sys.stderr)
        return 1

    write_seed(entries, output_path)
    section_count = sum(1 for level, _ in entries if level == "section")
    subsection_count = sum(1 for level, _ in entries if level == "subsection")
    print(
        f"[toc-seed] generated {output_path} "
        f"(sections={section_count}, subsections={subsection_count})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
