/**
 * Auto-generated by scripts/build_detail_page_js.py.
 *
 * This file is for the mini-program detail page only.
 * It intentionally excludes search-only metadata such as:
 *   - search
 *   - searchmeta
 *   - ranking
 *   - pinyin / pinyinAbbr and other search keys under search.*
 *
 * Top-level export:
 *   module.exports = { [id]: DetailRecord }
 *
 * DetailRecord core fields:
 *   - id: stable content id from meta.json:id
 *   - title: display title from meta.json:core.title
 *   - display_version: currently 2, meaning structured latex-first sections are available
 *   - sections: structured display sections built from raw tex before clean_tex
 *
 * DetailRecord metadata fields:
 *   - module: Logical module name from meta.json; source=module; why=Lets the detail page know the business module without using the directory name.
 *   - alias: Alternative titles or aliases; source=core.alias; why=Useful for secondary display, FAQ labels, or future content hints.
 *   - difficulty: Difficulty level; source=core.difficulty; why=Supports badges, filtering, or display of expected problem difficulty.
 *   - category: Primary topic category; source=core.category; why=Supports detail-page labeling and page-level context.
 *   - tags: Topic tags; source=core.tags; why=Useful for related content chips and page-level navigation.
 *   - core_summary: Short summary from core metadata; source=core.summary; why=Keeps a compact summary separate from the long cleaned `summary` field.
 *   - core_formula: Primary formula or theorem statement; source=math.core_formula; why=Usually the first math block the detail page wants to highlight.
 *   - related_formulas: Closely related formulas; source=math.related_formulas; why=Supports extended reading and future expandable formula panels.
 *   - variables: Variables used by the formula; source=math.variables; why=Helps the detail page explain notation without re-parsing the formula text.
 *     variables shape: [{ latex, description? }] so the front end can render variables as math.
 *   - conditions: Conditions under which the statement holds; source=math.conditions; why=Important guardrails for the detail page so conditions are easy to show.
 *   - conclusions: Main conclusion or equality case; source=math.conclusions; why=Lets the page show the takeaway without re-reading the full proof.
 *   - usage: Usage scenarios and problem types; source=usage; why=Supports 'when to use this' sections on the detail page.
 *   - interactive: Interactive page configuration; source=interactive; why=Keeps detail-page interactive affordances close to the content record.
 *   - assets: Static asset references; source=assets; why=The detail page can directly load svg, png, mp4, or other resources.
 *   - shareConfig: Share card title and description; source=shareConfig; why=Used directly by the mini-program sharing entry points.
 *   - relations: Prerequisites and related content; source=relations; why=Supports related-content blocks and learning-path navigation.
 *   - isPro: Premium or gated flag; source=isPro; why=Allows the page to show lock states or access messaging.
 *   - remarks: Free-form remarks; source=remarks; why=Keeps room for editorial notes without changing the schema.
 *   - knowledgeNode: Primary knowledge-tree node; source=knowledgeNode; why=Useful for breadcrumb-like display or curriculum linking.
 *   - altNodes: Alternative knowledge-tree nodes; source=altNodes; why=Supports cross-linking when one topic belongs to multiple paths.
 *
 * DetailRecord cleaned text fields:
 *   - statement: Main cleaned theorem/problem statement; source=01_statement.tex; fallback=content.statement; why=This is the primary content block shown at the top of the detail page.
 *   - explanation: Cleaned explanatory text; source=02_explanation.tex; fallback=none; why=Used for intuition, decomposition, and interpretation under the statement.
 *   - proof: Cleaned proof text; source=03_proof.tex; fallback=none; why=Keeps the formal derivation in display-ready plain text.
 *   - examples: Cleaned examples text; source=04_examples.tex; fallback=none; why=Supports worked examples or application snippets on the detail page.
 *   - traps: Cleaned common pitfalls text; source=05_traps.tex; fallback=content.common_tricks; why=Useful for mistake reminders and learning notes.
 *   - summary: Cleaned summary text; source=06_summary.tex; fallback=core.summary; why=Provides a concise end-of-page takeaway for quick review.
 *
 * Structured sections schema:
 *   - Section = { key, title, layout, items }
 *   - Supported item forms:
 *     1. { text: string }
 *     2. { latex: string }
 *     3. { segments: [{ type: 'text', text } | { type: 'math', latex }] }
 *     4. theorem-list item: { title, segments }
 *   - Rich parser rules for mixed text/math sections:
 *     - Long equation-chain math is promoted to standalone { latex } items.
 *     - Trailing punctuation is stripped out of latex and kept in text segments.
 *     - This improves canonical migration to math_block and avoids inline overflow.
 *   - Important layouts used by this builder:
 *     - text
 *     - theorem-list
 *   - Legacy plain-text fields remain in the record for compatibility and debugging.
 */
module.exports = {
  "S017": {
    "id": "S017",
    "title": "子集个数公式",
    "module": "set",
    "alias": [
      "子集计数",
      "2的n次方",
      "包含指定元素子集",
      "子集数量公式"
    ],
    "difficulty": 2,
    "category": "计数原理",
    "tags": [
      "子集计数",
      "分类加法",
      "分步乘法",
      "组合数学基础",
      "二项式系数"
    ],
    "core_summary": "有限集的子集个数为2的n次方；若强制包含某些元素，则剩下元素自由组合，个数为2的n-m次方。",
    "core_formula": "2^{n}",
    "related_formulas": [
      "2^{n-m}",
      "N = N_1+N_2+\\cdots+N_k",
      "N = n_1 n_2 \\cdots n_m"
    ],
    "variables": [
      {
        "latex": "n: 集合元素个数"
      },
      {
        "latex": "m: 指定包含的元素个数"
      },
      {
        "latex": "N: 子集总数"
      },
      {
        "latex": "N_i: 第i类子集个数"
      },
      {
        "latex": "n_i: 第i步的选择数"
      }
    ],
    "conditions": [
      "集合A是有限集，元素个数n≥0",
      "元素的选取相互独立，无耦合限制",
      "分类时各类互斥",
      "分步时各步独立"
    ],
    "conclusions": [
      "所有子集个数为2^n",
      "包含指定m个元素的子集个数为2^{n-m}",
      "互斥分类时总数为各类之和",
      "独立分步时总数为各步之积"
    ],
    "usage": {
      "scenarios": [
        "子集计数问题",
        "组合计数基础",
        "排列组合入门"
      ],
      "problem_types": [
        "求子集个数",
        "含条件子集计数",
        "分类计数"
      ],
      "exam_frequency": 1,
      "exam_score": 5
    },
    "interactive": {
      "has_diagram": false,
      "geogebra_id": "",
      "param_demo": {}
    },
    "assets": {
      "svg": "S017.svg",
      "png": "",
      "pdf": "",
      "video": ""
    },
    "shareConfig": {
      "title": "子集计数公式：直接套用2^n避免遗漏",
      "shareDesc": "适合课后复盘和刷题前速查，直接套用公式计算子集个数，避免分类遗漏或重复计数，提升计数题第一步的准确率。"
    },
    "relations": {
      "prerequisites": [
        "集合基本概念",
        "乘法原理"
      ],
      "related_ids": [],
      "similar": [
        "二项式系数之和为2^n",
        "元素选取的计数模型"
      ]
    },
    "isPro": 0,
    "remarks": "",
    "knowledgeNode": "概率-古典概型-排列组合",
    "altNodes": "",
    "statement": "条件\n- 条件 1（有限集合）： 设 A 为含有 n 个元素的有限集（n in N）。\n结论\n- 结论一（所有子集）：\n直观描述：\n每个元素独立决定“取”或“不取”，n 次选择产生 2^n 种组合。\n|P(A)| = 2^n.\n- 结论二（含指定元素）：\n直观描述：\n强制包含的 m 个元素无选择权，其余 n-m 个元素自由组合。\nN = 2^\\,n-m.\n- 推广结论（加法乘法原理）：\n直观描述：\n互斥情形用加法串联，独立步骤用乘法串联。\nN = N_1 + N_2 + * s + N_k,\nN = n_1 n_2 * s n_m.\n参数限制：\n要求 n 为非负整数，m 为整数且满足 0 m n。当 m=0 时，公式 2^n-m 退化为 2^n；当 m=n 时，结果为 2^0=1，即仅有全集。",
    "explanation": "一句话直觉\n子集个数的本质是每个元素独立二选一的决策树，结果是 2^n。\n核心拆解\n- 要点一（独立二选一）： 每个元素的“取”与“不取”构成一个二岔路口，n 个元素形成 n 级决策树，总叶节点数恰为 2^n。\n- 要点二（强制包含排除）： 若某些元素被强制选择或禁止，其对应分支被固定，实际决策级数减少为 n-m，故总数降为 2^n-m。\n几何本质（决策二叉树）\n将子集生成过程画成二叉树：第 1 层对应第 1 个元素，向左表示不取，向右表示取；依此类推，n 层后共有 2^n 条路径，每条路径唯一对应一个子集。包含指定元素则相当于在对应层上强制走右分支，路径数折半。\n代数意义（幂运算模型）\n公式 2^n 是指数函数的最简模型，反映“翻倍”特性：每增加一个元素，子集数翻倍。在代数上，(1+1)^n 的二项式展开 C_n^0 + C_n^1 + * s + C_n^n = 2^n 也揭示了子集个数与组合数的恒等关系。\n考点价值（原理辨析）\n- 考法一（直接套公式）： 给出集合元素个数，直接求所有子集数或满足简单包含关系的子集数。\n- 考法二（原理易混）： 故意将分类加法与分步乘法交错呈现，要求学生准确判断何时用加、何时用乘，以及分类是否互斥。\n顿悟点\n空集和全集也是合法的子集，因为它们对应“全不取”和“全取”两种决策组合。因此公式中 2^n 无需减去任何项。\n使用场景\n- 场景一（样本空间计数）： 求随机试验中样本点的个数，如掷硬币 n 次的结果空间大小为 2^n。\n- 场景二（条件筛选）： 在集合中筛选满足“必含某元素、不含某元素”等条件的子集时，先固化指定元素，再对剩余元素套用 2^n-m。\n- 场景三（复杂条件拆分）： 当条件无法直接表达为“包含指定元素”时，可尝试将条件分解为互斥类，再分类套用公式并相加。",
    "proof": "思路提示\n将子集构造视为对每个元素给出“是/否”判断的序列，然后应用乘法原理。\n正式推导\n- 步骤一（元素决策模型）： 对 A 中的元素依次决定其归属。每个元素恰有 2 种可能：属于子集（记为 1），或不属于（记为 0）。\nc_i = 2 (i=1, ,n).\n理由： 子集由布尔向量唯一确定。\n- 步骤二（应用乘法原理）： 因为 n 个元素的选择相互独立，根据分步乘法原理，总的决策序列数等于各元素选择数之积。\nN = _i=1^n 2 = 2^n.\n理由： 乘法原理的经典形式，这里每个元素贡献因子 2。\n- 步骤三（包含指定元素的情形）： 若已知某 m 个元素必须属于子集，则这 m 个元素各自只余 1 种选择（强制取），剩余 n-m 个元素仍各有 2 种选择。由乘法原理，\nN' = 1 * * s * 1_m * 2 * * s * 2_n-m = 2^\\,n-m.\n理由： 固定元素贡献因子 1，不影响乘积的倍数性质；实际共有 m 个 1 和 n-m 个 2。\n- 步骤四（一般原理的自然导出）： 一般地，若附加条件可将子集分为互斥的 k 类，且各类已分别求出个数 N_i，由加法原理，总数为 N_1+ * s+N_k；若条件是通过 m 个独立步骤来施加，且第 i 步有 n_i 种合法选择，则由乘法原理，总数为 n_1 n_2 * s n_m。这正是对前面特例的推广。\n理由： 分类加法与分步乘法是计数的两个基本公理，本结论揭示了其典型应用。\n结论回扣\n子集计数问题最终归结为每个元素的独立二选一；特殊元素“必选”或“必不选”相当于减少独立元素的个数，从而改变了指数。推广原理则提供了处理复杂约束的通用框架。",
    "examples": "例 1（基础）\n题目：\n已知集合 A = \\a, b, c, d\\。求：(1) A 的所有子集个数；(2) 包含元素 a 的子集个数。\n解题步骤：\n- 第一步（读出参数）： 集合 A 共有 4 个元素，故 n=4；涉及包含 a 时，指定元素个数 m=1。\n理由： 直接计数元素即可。\n- 第二步（计算所有子集）： 由公式 2^n 得：\n2^4 = 16.\n理由： 套用子集总数公式。\n- 第三步（计算含 a 的子集）： 将 n=4, m=1 代入 2^n-m，得：\n2^4-1 = 2^3 = 8.\n理由： 使用包含指定元素的公式。\n关键结论：\n当条件只是简单的“包含某几个元素”时，直接代公式计算。\n例 2（稍变形）\n题目：\n集合 B 含有 5 个元素，问同时包含指定的某 2 个元素的子集有多少个？\n解题步骤：\n- 第一步（确定参数）： n=5，指定的 2 个元素构成 m=2。\n理由： 从题中读取基本量。\n- 第二步（排除无关元素）： 由于只关心这 2 个元素必须出现，其余 n-m=3 个元素自由选择。\n理由： 固定元素的选择已唯一确定。\n- 第三步（代入公式）： 子集个数为：\n2^5-2 = 2^3 = 8.\n理由： 直接应用公式 2^n-m。\n关键结论：\n即使题目未直接给出“指定元素个数”，也要能根据“同时包含”识别出 m。\n例 3（综合应用）\n题目：\n设集合 U = \\1,2,3,4,5\\，求满足“包含元素 1 但不含元素 2”的子集个数。\n解题步骤：\n- 第一步（条件转化）： 条件“不含 2”等价于子集必须从 U \\2\\ 中选取，故可先将 2 移除，全集缩小为 V = \\1,3,4,5\\，其元素个数为 4（即新的 n'=4）。\n理由： 排除禁止元素，缩小选择范围。\n- 第二步（应用包含公式）： 在 V 中又要求含元素 1，此时指定元素个数 m=1。\n理由： 将问题转化为基本模型。\n- 第三步（计算）： 所求个数为：\n2^4-1 = 2^3 = 8.\n理由： 直接代入 2^n'-m；也可用分步乘法：元素 1 必选（1 种），元素 2 必不选（1 种），其余 3 个元素任选（各 2 种），得 1 * 1 * 2^3 = 8。\n关键结论：\n遇到“不含某元素”时，可通过缩小全集，然后在新集合上直接套用包含公式。",
    "traps": "- 易错点一（忽略空集） 误以为子集个数是 2^n - 1，漏掉了空集或全集。\n- 正确理解（全集在内）： 空集和全集都是合法的子集，总个数恰为 2^n，无需额外减 1。\n- 错因分析（概念混淆）： 常将“子集”与“非空子集”或“真子集”混淆，没有注意到决定子集时“全不选”也是一种合法决策。\n- 易错点二（包含当仅含） 把“包含指定元素”误解为“恰好由这些元素组成”，从而错误地排除其它元素。\n- 正确理解（至少包含）： 公式 2^n-m 计数的是所有至少含这 m 个元素的子集，它们仍可包含其余元素，因此是 2^n-m 而非 1 或别的数。\n- 错因分析（语义偏差）： 对自然语言“包含”在组合数学中的一般含义（至少包含）理解不准确，忽略了“可以多含”的默认约定。\n- 易错点三（分类重叠加法） 在使用分类加法原理时，未检查各类是否互斥，若类别有重叠，直接相加会造成重复计数。\n- 正确理解（需先判互斥）： 分类加法原理的成立前提是“不重不漏”；若发现重叠，必须调整分类或改用容斥原理（如系数修正）。\n- 错因分析（盲目套用）： 看到题目中有“或”就习惯性地用加法，未先厘清条件所对应的子集是否有交集。",
    "summary": "一句话核心\n子集个数公式 2^n 的核心是“每个元素独立二选一”的乘法原理；包含指定 m 个元素时，相当于强制 m 个元素选“是”，剩余元素仍二选一，故为 2^n-m。\n使用条件\n- 条件 1（有限集）： A 必须为有限集，元素个数 n 0。\n- 条件 2（独立可选）： 元素的选取（或决策）相互独立，无附加耦合限制（如“最多选 k 个”这类限制不适用简单公式）。\n关键提醒\n- 易错点（漏空集/全集）： 切勿遗忘空集（全不选）和全集（全选），它们使总数达到 2^n。\n- 检查项（判互斥再加法）： 使用分类加法前，一定先检查分类是否互斥。",
    "display_version": 2,
    "sections": [
      {
        "key": "core_formula",
        "title": "核心公式",
        "layout": "text",
        "items": [
          {
            "latex": "2^{n}"
          }
        ]
      },
      {
        "key": "variables",
        "title": "涉及变量",
        "layout": "text",
        "items": [
          {
            "latex": "n: 集合元素个数"
          },
          {
            "latex": "m: 指定包含的元素个数"
          },
          {
            "latex": "N: 子集总数"
          },
          {
            "latex": "N_i: 第i类子集个数"
          },
          {
            "latex": "n_i: 第i步的选择数"
          }
        ]
      },
      {
        "key": "statement",
        "title": "命题表述",
        "layout": "theorem-list",
        "items": [
          {
            "title": "条件 1（有限集合）：",
            "segments": [
              {
                "type": "text",
                "text": "设"
              },
              {
                "type": "math",
                "latex": "A"
              },
              {
                "type": "text",
                "text": "为含有"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "个元素的有限集（"
              },
              {
                "type": "math",
                "latex": "n\\in\\mathbb{N}"
              },
              {
                "type": "text",
                "text": "）。"
              }
            ]
          },
          {
            "title": "结论一（所有子集）：",
            "segments": [
              {
                "type": "text",
                "text": "每个元素独立决定“取”或“不取”，"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "次选择产生"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "种组合。"
              },
              {
                "type": "math",
                "latex": "|\\mathcal{P}(A)| = 2^n."
              }
            ]
          },
          {
            "title": "结论二（含指定元素）：",
            "segments": [
              {
                "type": "text",
                "text": "强制包含的"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个元素无选择权，其余"
              },
              {
                "type": "math",
                "latex": "n-m"
              },
              {
                "type": "text",
                "text": "个元素自由组合。"
              },
              {
                "type": "math",
                "latex": "N = 2^{\\,n-m}."
              }
            ]
          },
          {
            "title": "推广结论（加法乘法原理）：",
            "segments": [
              {
                "type": "text",
                "text": "互斥情形用加法串联，独立步骤用乘法串联。"
              },
              {
                "type": "math",
                "latex": "N = N_1 + N_2 + \\cdots + N_k,"
              },
              {
                "type": "math",
                "latex": "N = n_1 n_2 \\cdots n_m."
              },
              {
                "type": "text",
                "text": "参数限制：\n要求"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "为非负整数，"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "为整数且满足"
              },
              {
                "type": "math",
                "latex": "0 \\le m \\le n"
              },
              {
                "type": "text",
                "text": "。当"
              },
              {
                "type": "math",
                "latex": "m=0"
              },
              {
                "type": "text",
                "text": "时，公式"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "退化为"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "；当"
              },
              {
                "type": "math",
                "latex": "m=n"
              },
              {
                "type": "text",
                "text": "时，结果为"
              },
              {
                "type": "math",
                "latex": "2^0=1"
              },
              {
                "type": "text",
                "text": "，即仅有全集。"
              }
            ]
          }
        ]
      },
      {
        "key": "explanation",
        "title": "理解与直觉",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "一句话直觉\n子集个数的本质是每个元素独立二选一的决策树，结果是"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "核心拆解"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "要点一（独立二选一）：\n每个元素的“取”与“不取”构成一个二岔路口，"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "个元素形成"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "级决策树，总叶节点数恰为"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "要点二（强制包含排除）：\n若某些元素被强制选择或禁止，其对应分支被固定，实际决策级数减少为"
              },
              {
                "type": "math",
                "latex": "n-m"
              },
              {
                "type": "text",
                "text": "，故总数降为"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "几何本质（决策二叉树）\n将子集生成过程画成二叉树：第"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "层对应第"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "个元素，向左表示不取，向右表示取；依此类推，"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "层后共有"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "条路径，每条路径唯一对应一个子集。包含指定元素则相当于在对应层上强制走右分支，路径数折半。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "代数意义（幂运算模型）\n公式"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "是指数函数的最简模型，反映“翻倍”特性：每增加一个元素，子集数翻倍。在代数上，"
              },
              {
                "type": "math",
                "latex": "(1+1)^n"
              },
              {
                "type": "text",
                "text": "的二项式展开"
              }
            ]
          },
          {
            "latex": "C_n^0 + C_n^1 + \\cdots + C_n^n = 2^n"
          },
          {
            "text": "也揭示了子集个数与组合数的恒等关系。"
          },
          {
            "text": "考点价值（原理辨析）"
          },
          {
            "text": "考法一（直接套公式）： 给出集合元素个数，直接求所有子集数或满足简单包含关系的子集数。"
          },
          {
            "text": "考法二（原理易混）： 故意将分类加法与分步乘法交错呈现，要求学生准确判断何时用加、何时用乘，以及分类是否互斥。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "顿悟点\n空集和全集也是合法的子集，因为它们对应“全不取”和“全取”两种决策组合。因此公式中"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "无需减去任何项。"
              }
            ]
          },
          {
            "text": "使用场景"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "场景一（样本空间计数）： 求随机试验中样本点的个数，如掷硬币"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "次的结果空间大小为"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "场景二（条件筛选）： 在集合中筛选满足“必含某元素、不含某元素”等条件的子集时，先固化指定元素，再对剩余元素套用"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "场景三（复杂条件拆分）： 当条件无法直接表达为“包含指定元素”时，可尝试将条件分解为互斥类，再分类套用公式并相加。"
          }
        ]
      },
      {
        "key": "proof",
        "title": "证明过程",
        "layout": "text",
        "items": [
          {
            "text": "思路提示\n将子集构造视为对每个元素给出“是/否”判断的序列，然后应用乘法原理。"
          },
          {
            "text": "正式推导"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤一（元素决策模型）：\n对"
              },
              {
                "type": "math",
                "latex": "A"
              },
              {
                "type": "text",
                "text": "中的元素依次决定其归属。每个元素恰有"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "种可能：属于子集（记为"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "），或不属于（记为"
              },
              {
                "type": "math",
                "latex": "0"
              },
              {
                "type": "text",
                "text": "）。"
              }
            ]
          },
          {
            "latex": "c_i = 2 \\quad (i=1,\\dots,n)"
          },
          {
            "text": ".理由： 子集由布尔向量唯一确定。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤二（应用乘法原理）：\n因为"
              },
              {
                "type": "math",
                "latex": "n"
              },
              {
                "type": "text",
                "text": "个元素的选择相互独立，根据分步乘法原理，总的决策序列数等于各元素选择数之积。"
              }
            ]
          },
          {
            "latex": "N = \\prod_{i=1}^{n} 2 = 2^n"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".理由： 乘法原理的经典形式，这里每个元素贡献因子"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤三（包含指定元素的情形）：\n若已知某"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个元素必须属于子集，则这"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个元素各自只余"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "种选择（强制取），剩余"
              },
              {
                "type": "math",
                "latex": "n-m"
              },
              {
                "type": "text",
                "text": "个元素仍各有"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "种选择。由乘法原理，"
              }
            ]
          },
          {
            "latex": "N' = \\underbrace{1 \\times \\cdots \\times 1}_{m} \\times \\underbrace{2 \\times \\cdots \\times 2}_{n-m} = 2^{\\,n-m}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": ".理由： 固定元素贡献因子"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "，不影响乘积的倍数性质；实际共有"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "和"
              },
              {
                "type": "math",
                "latex": "n-m"
              },
              {
                "type": "text",
                "text": "个"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "步骤四（一般原理的自然导出）：\n一般地，若附加条件可将子集分为互斥的"
              },
              {
                "type": "math",
                "latex": "k"
              },
              {
                "type": "text",
                "text": "类，且各类已分别求出个数"
              },
              {
                "type": "math",
                "latex": "N_i"
              },
              {
                "type": "text",
                "text": "，由加法原理，总数为"
              }
            ]
          },
          {
            "latex": "N_1+\\cdots+N_k"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "；若条件是通过"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个独立步骤来施加，且第"
              },
              {
                "type": "math",
                "latex": "i"
              },
              {
                "type": "text",
                "text": "步有"
              },
              {
                "type": "math",
                "latex": "n_i"
              },
              {
                "type": "text",
                "text": "种合法选择，则由乘法原理，总数为"
              }
            ]
          },
          {
            "latex": "n_1 n_2 \\cdots n_m"
          },
          {
            "text": "。这正是对前面特例的推广。\n理由： 分类加法与分步乘法是计数的两个基本公理，本结论揭示了其典型应用。"
          },
          {
            "text": "结论回扣\n子集计数问题最终归结为每个元素的独立二选一；特殊元素“必选”或“必不选”相当于减少独立元素的个数，从而改变了指数。推广原理则提供了处理复杂约束的通用框架。"
          }
        ]
      },
      {
        "key": "examples",
        "title": "例题应用",
        "layout": "text",
        "items": [
          {
            "text": "例 1（基础）\n题目：\n已知集合"
          },
          {
            "latex": "A = \\{a, b, c, d\\}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "。求：(1)"
              },
              {
                "type": "math",
                "latex": "A"
              },
              {
                "type": "text",
                "text": "的所有子集个数；(2) 包含元素"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "的子集个数。\n解题步骤："
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第一步（读出参数）：\n集合"
              },
              {
                "type": "math",
                "latex": "A"
              },
              {
                "type": "text",
                "text": "共有"
              },
              {
                "type": "math",
                "latex": "4"
              },
              {
                "type": "text",
                "text": "个元素，故"
              },
              {
                "type": "math",
                "latex": "n=4"
              },
              {
                "type": "text",
                "text": "；涉及包含"
              },
              {
                "type": "math",
                "latex": "a"
              },
              {
                "type": "text",
                "text": "时，指定元素个数"
              },
              {
                "type": "math",
                "latex": "m=1"
              },
              {
                "type": "text",
                "text": "。\n理由： 直接计数元素即可。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第二步（计算所有子集）：\n由公式"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "得："
              },
              {
                "type": "math",
                "latex": "2^4 = 16"
              },
              {
                "type": "text",
                "text": ".理由： 套用子集总数公式。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第三步（计算含 的子集）：\n将"
              },
              {
                "type": "math",
                "latex": "n=4, m=1"
              },
              {
                "type": "text",
                "text": "代入"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "，得："
              },
              {
                "type": "math",
                "latex": "2^{4-1} = 2^3 = 8"
              },
              {
                "type": "text",
                "text": ".理由： 使用包含指定元素的公式。\n关键结论：\n当条件只是简单的“包含某几个元素”时，直接代公式计算。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "例 2（稍变形）\n题目：\n集合"
              },
              {
                "type": "math",
                "latex": "B"
              },
              {
                "type": "text",
                "text": "含有"
              },
              {
                "type": "math",
                "latex": "5"
              },
              {
                "type": "text",
                "text": "个元素，问同时包含指定的某"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "个元素的子集有多少个？\n解题步骤："
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第一步（确定参数）："
              },
              {
                "type": "math",
                "latex": "n=5"
              },
              {
                "type": "text",
                "text": "，指定的"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "个元素构成"
              },
              {
                "type": "math",
                "latex": "m=2"
              },
              {
                "type": "text",
                "text": "。\n理由： 从题中读取基本量。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第二步（排除无关元素）：\n由于只关心这"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "个元素必须出现，其余"
              },
              {
                "type": "math",
                "latex": "n-m=3"
              },
              {
                "type": "text",
                "text": "个元素自由选择。\n理由： 固定元素的选择已唯一确定。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第三步（代入公式）：\n子集个数为："
              },
              {
                "type": "math",
                "latex": "2^{5-2} = 2^3 = 8"
              },
              {
                "type": "text",
                "text": ".理由： 直接应用公式"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "。\n关键结论：\n即使题目未直接给出“指定元素个数”，也要能根据“同时包含”识别出"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "例 3（综合应用）\n题目：\n设集合"
          },
          {
            "latex": "U = \\{1,2,3,4,5\\}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，求满足“包含元素"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "但不含元素"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "”的子集个数。\n解题步骤："
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第一步（条件转化）：\n条件“不含"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "”等价于子集必须从"
              }
            ]
          },
          {
            "latex": "U \\setminus \\{2\\}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "中选取，故可先将"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "移除，全集缩小为"
              }
            ]
          },
          {
            "latex": "V = \\{1,3,4,5\\}"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "，其元素个数为"
              },
              {
                "type": "math",
                "latex": "4"
              },
              {
                "type": "text",
                "text": "（即新的"
              },
              {
                "type": "math",
                "latex": "n'=4"
              },
              {
                "type": "text",
                "text": "）。\n理由： 排除禁止元素，缩小选择范围。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第二步（应用包含公式）：\n在"
              },
              {
                "type": "math",
                "latex": "V"
              },
              {
                "type": "text",
                "text": "中又要求含元素"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "，此时指定元素个数"
              },
              {
                "type": "math",
                "latex": "m=1"
              },
              {
                "type": "text",
                "text": "。\n理由： 将问题转化为基本模型。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "第三步（计算）：\n所求个数为："
              },
              {
                "type": "math",
                "latex": "2^{4-1} = 2^3 = 8"
              },
              {
                "type": "text",
                "text": ".理由： 直接代入"
              },
              {
                "type": "math",
                "latex": "2^{n'-m}"
              },
              {
                "type": "text",
                "text": "；也可用分步乘法：元素"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "必选（"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "种），元素"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "必不选（"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "种），其余"
              },
              {
                "type": "math",
                "latex": "3"
              },
              {
                "type": "text",
                "text": "个元素任选（各"
              },
              {
                "type": "math",
                "latex": "2"
              },
              {
                "type": "text",
                "text": "种），得"
              }
            ]
          },
          {
            "latex": "1 \\times 1 \\times 2^3 = 8"
          },
          {
            "text": "。\n关键结论：\n遇到“不含某元素”时，可通过缩小全集，然后在新集合上直接套用包含公式。"
          }
        ]
      },
      {
        "key": "traps",
        "title": "易错提醒",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点一（忽略空集）\n误以为子集个数是"
              },
              {
                "type": "math",
                "latex": "2^n - 1"
              },
              {
                "type": "text",
                "text": "，漏掉了空集或全集。"
              }
            ]
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解（全集在内）：\n空集和全集都是合法的子集，总个数恰为"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "，无需额外减"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "错因分析（概念混淆）：\n常将“子集”与“非空子集”或“真子集”混淆，没有注意到决定子集时“全不选”也是一种合法决策。"
          },
          {
            "text": "易错点二（包含当仅含）\n把“包含指定元素”误解为“恰好由这些元素组成”，从而错误地排除其它元素。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "正确理解（至少包含）：\n公式"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "计数的是所有至少含这"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个元素的子集，它们仍可包含其余元素，因此是"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "而非"
              },
              {
                "type": "math",
                "latex": "1"
              },
              {
                "type": "text",
                "text": "或别的数。"
              }
            ]
          },
          {
            "text": "错因分析（语义偏差）：\n对自然语言“包含”在组合数学中的一般含义（至少包含）理解不准确，忽略了“可以多含”的默认约定。"
          },
          {
            "text": "易错点三（分类重叠加法）\n在使用分类加法原理时，未检查各类是否互斥，若类别有重叠，直接相加会造成重复计数。"
          },
          {
            "text": "正确理解（需先判互斥）：\n分类加法原理的成立前提是“不重不漏”；若发现重叠，必须调整分类或改用容斥原理（如系数修正）。"
          },
          {
            "text": "错因分析（盲目套用）：\n看到题目中有“或”就习惯性地用加法，未先厘清条件所对应的子集是否有交集。"
          }
        ]
      },
      {
        "key": "summary",
        "title": "复盘总结",
        "layout": "text",
        "items": [
          {
            "segments": [
              {
                "type": "text",
                "text": "一句话核心\n子集个数公式"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "的核心是“每个元素独立二选一”的乘法原理；包含指定"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个元素时，相当于强制"
              },
              {
                "type": "math",
                "latex": "m"
              },
              {
                "type": "text",
                "text": "个元素选“是”，剩余元素仍二选一，故为"
              },
              {
                "type": "math",
                "latex": "2^{n-m}"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "使用条件"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "条件 1（有限集）："
              },
              {
                "type": "math",
                "latex": "A"
              },
              {
                "type": "text",
                "text": "必须为有限集，元素个数"
              }
            ]
          },
          {
            "latex": "n \\ge 0"
          },
          {
            "text": "。"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "条件 2（独立可选）： 元素的选取（或决策）相互独立，无附加耦合限制（如“最多选"
              },
              {
                "type": "math",
                "latex": "k"
              },
              {
                "type": "text",
                "text": "个”这类限制不适用简单公式）。"
              }
            ]
          },
          {
            "text": "关键提醒"
          },
          {
            "segments": [
              {
                "type": "text",
                "text": "易错点（漏空集/全集）： 切勿遗忘空集（全不选）和全集（全选），它们使总数达到"
              },
              {
                "type": "math",
                "latex": "2^n"
              },
              {
                "type": "text",
                "text": "。"
              }
            ]
          },
          {
            "text": "检查项（判互斥再加法）： 使用分类加法前，一定先检查分类是否互斥。"
          }
        ]
      }
    ]
  }
}
